In [4]:
import pandas as pd
import numpy as np
census=pd.read_csv('NDAP_REPORT_6000.csv')

pd.set_option('display.max_columns', None)

In [5]:
state_totals = census.groupby('State').agg({'Population': 'sum','Literate population ':'sum','Male population':'sum', 'Male literate population': 'sum' ,'Female population':'sum', 'Female literate population ':'sum',})

In [5]:
census

,ROWID,Country,State lgd code,State,District lgd code,District,Sub-District lgd Code,Sub-District,ULB_RLB_Village lgd Code,ULB_RLB_Village,Rural or Urban,Households,Population,Male population,Female population,Population in the age group 0 to 6 years,Male Population in the age group 0 to 6 years,Female Population in the age group 0 to 6 years,Scheduled Caste population,Male Scheduled Caste population,Female Scheduled Caste population,Scheduled Tribe population,Male Scheduled Tribe population,Female Scheduled Tribe population,Literate population,Male literate population,Female literate population,Illiterate population,Male illiterate population,Female illiterate population,Working population,Male working population,Female Woking population,Number of main workers,Number of male main workers,Number of female main worker,Number of main workers as cultivators,Number of male main workers as cultivators,Number of female main workers as cultivators,Number of main workers as agricultural labourers,Number of male main workers as agricultural labourers,Number of female main workers as agricultural labourers,Number of main workers in the household industry,Number of male main workers in the household industry,Number of female main workers in the household industry,Number of main workers as Other workers,Number of male main workers as Other workers,Number of female main workers as Other workers,Number of marginal workers,Number of male marginal workers,Number of female marginal workers,Number of marginal workers as cultivators,Number of male marginal workers as cultivators,Number of female marginal workers as cultivators,Number of marginal workers as agricultural labourers,Number of male marginal workers as agricultural labourers,Number of female marginal workers as agricultural labourers,Number of marginal workers in the household industry,Number of male marginal workers in the household industry,Number of female marginal workers in the household industry,Number of marginal workers as Other workers,Number of male marginal workers as Other workers,Number of female marginal workers as Other workers,Number of marginal workers who worked for 3 to 6 months,Number of male marginal workers who worked for 3 to 6 months,Number of female marginal workers who worked for 3 to 6 months,Total Number of marginal workers as cultivators who worked for 3 to 6 months,Number of male marginal workers as cultivators who worked for 3 to 6 months,Number of female marginal workers as cultivators who worked for 3 to 6 months,Number of marginal workers as agricultural labour who worked for 3 to 6 months,Number of male marginal workers as agricultural labour who worked for 3 to 6 months,Number of female marginal workers as agricultural labour who worked for 3 to 6 months,Number of marginal workers in household industry who worked for 3 to 6 months,Number of male marginal workers in household industry who worked for 3 to 6 months,Number of female marginal workers in household industry who worked for 3 to 6 months,Number of marginal workers as Other workers who worked for 3 to 6 months,Number of male marginal workers as Other workers who worked for 3 to 6 months,Number of female marginal workers as Other workers who worked for 3 to 6 months,Number of marginal workers who worked for 0 to 3 months,Number of male marginal workers who worked for 0 to 3 months,Number of female marginal workers who worked for 0 to 3 months,Number of marginal workers as cultivators who worked for 0 to 3 months,Number of male marginal workers as cultivators who worked for 0 to 3 months,Number of female marginal workers as cultivators who worked for 0 to 3 months,Total nuumber of marginal workers as agricultural labour who worked for 0 to 3 months,Number of male marginal workers in agricultural labour who worked for 0 to 3 months,Number of female marginal workers as agricultural labour who worked for 0 to 3 months,Number of marginal workers in household industry who worked for 0 to 3 months,Number of male marginal workers in household industry who worked for 0 to 3 months,Number of female marginal workers in household industry who worked for 0 to 3 months,Number of marginal workers as Other workers who worked for 0 to 3 months,Number of male marginal workers as Other workers who worked for 0 to 3 months,Number of female marginal workers as Other workers who worked for 0 to 3 months,Number of Non workers,Number of male Non workers,Number of female Non workers,Source Year,YearCode,Year
0,585,India,24,GUJARAT,442,BHARUCH,999999,Unknown SubDistricts of India,9802612,Valia (Naldhari) (INA),Urban,1,5,5,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,5,5,0,5,5,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2011,2011,"Calendar Year (Jan - Dec), 2011"
1,637,India,24,GUJARAT,459,SURAT,3937,Majura,802631,Surat,Urban,5,18,18,0,0,0,0,0,0,0,0,0,0,15,15,0,3,3,0,18,18,0,18,18,0,0,0,0,0,0,0,0,0,0,18,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2011,2011,"Calendar Year (Jan - Dec), 2011"
2,1498,India,21,ODISHA,350,CUTTACK,2954,Choudwar,399316,Industrial Area (OG),Urban,2,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,2,2,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,2011,2011,"Calendar Year (Jan - Dec), 2011"
3,2062,India,5,UTTARAKHAND,54,RUDRA PRAYAG,290,Ukhimath,800296,Kedarnath,Urban,297,612,609,3,0,0,0,26,26,0,0,0,0,601,599,2,11,10,1,604,601,3,601,598,3,1,1,0,0,0,0,0,0,0,600,597,3,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,0,2011,2011,"Calendar Year (Jan - Dec), 2011"
4,4150,India,1,JAMMU AND KASHMIR,3,BARAMULLA,39,Tangmarg,800009,Municipal Committee Gulmarg Tangmarg,Urban,77,1965,1957,8,0,0,0,12,12,0,3,3,0,1950,1942,8,15,15,0,1962,1956,6,1962,1956,6,3,3,0,0,0,0,0,0,0,1959,1953,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,2,2011,2011,"Calendar Year (Jan - Dec), 2011"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606673,550918,India,36,TELANGANA,698,VIKARABAD,4539,Kulkacharla,574602,Mujahidpur,Rural,1010,5344,2801,2543,667,340,327,616,306,310,1917,1038,879,2550,1639,911,2794,1162,1632,2605,1313,1292,1470,806,664,551,372,179,325,75,250,58,27,31,536,332,204,1135,507,628,215,115,100,753,297,456,36,20,16,131,75,56,1109,496,613,212,114,98,742,293,449,34,19,15,121,70,51,26,11,15,3,1,2,11,4,7,2,1,1,10,5,5,2739,1488,1251,2011,2011,"Calendar Year (Jan - Dec), 2011"
606674,279202,India,36,TELANGANA,698,VIKARABAD,4541,Pudur,574685,Sirgaipalle,Rural,127,651,347,304,80,47,33,0,0,0,2,2,0,381,231,150,270,116,154,174,100,74,125,70,55,54,30,24,60,30,30,1,0,1,10,10,0,49,30,19,22,13,9,9,6,3,2,1,1,16,10,6,47,28,19,21,12,9,8,5,3,2,1,1,16,10,6,2,2,0,1,1,0,1,1,0,0,0,0,0,0,0,477,247,230,2011,2011,"Calendar Year (Jan - Dec), 2011"
606675,45447,India,36,TELANGANA,699,KUMURAM BHEEM ASIFABAD,4318,Kagaznagar,569470,Jambuga,Rural,25,107,54,53,13,8,5,0,0,0,0,0,0,51,27,24,56,27,29,60,34,26,45,30,15,16,12,4,24,15,9,0,0,0,5,3,2,15,4,11,3,1,2,12,3,9,0,0,0,0,0,0,15,4,11,3,1,2,12,3,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,20,27,2011,2011,"Calendar Year (Jan - Dec), 2011"
606676,122623,India,37,LADAKH,6,KARGIL,15,Zanskar,1066,Hamiling,Rural,48,266,116,150,40,20,20,0,0,0,264,114,150,133,57,76,133,59,74,130,60,70,12,10,2,0,0,0,0,0,0,1,1,0,11,9,2,118,50,68,2,1,1,110,46,64,1,0,1,5,3,2,118,50,68,2,1,1,110,46,64,1,0,1,5,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,136,56,80,2011,2011,"Calendar Year (Jan - Dec), 2011"
606677,206923,India,37,LADAKH,9,LEH LADAKH,10,Leh,857,Nang,Rural,74,334,156,178,44,24,20,0,0,0,333,156,177,175,94,81,159,62,97,95,68,27,37,24,13,3,2,1,0,0,0,0,0,0,34,22,12,58,44,14,50,39,11,0,0,0,0,0,0,8,5,3,58,44,14,50,39,11,0,0,0,0,0,0,8,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,239,88,151,2011,2011,"Calendar Year (Jan - Dec), 2011"

In [7]:

state_totals['Total Literacy Rate'] = state_totals['Literate population '] / state_totals['Population']

In [10]:

state_totals['Male Literacy Rate'] = state_totals['Male literate population'] / state_totals['Male population']

In [11]:

state_totals['Female Literacy Rate'] = state_totals['Female literate population '] / state_totals['Female population']

In [12]:
state_totals

,Population,Literate population,Male population,Male literate population,Female population,Female literate population,Total Literacy Rate,Male Literacy Rate,Female Literacy Rate
State,,,,,,,,,
ANDAMAN AND NICOBAR ISLANDS,380581,294281,202871,164377,177710,129904,0.773241,0.810254,0.730989
ANDHRA PRADESH,49577103,29859982,24830513,16549514,24746590,13310468,0.602294,0.666499,0.537871
ARUNACHAL PRADESH,1383727,766005,713912,439868,669815,326137,0.553581,0.616138,0.486906
ASSAM,31205576,19177977,15939443,10568639,15266133,8609338,0.614569,0.663049,0.563950
BIHAR,104099452,52504553,54278157,31608023,49821295,20896530,0.504369,0.582334,0.419430
CHANDIGARH,1055450,805438,580663,465346,474787,340092,0.763123,0.801405,0.716304
CHHATTISGARH,25545198,15379922,12832895,8807893,12712303,6572029,0.602067,0.686353,0.516982
DELHI,16787941,12737767,8987326,7194856,7800615,5542911,0.758745,0.800556,0.710574
GOA,1458545,1165487,739140,615823,719405,549664,0.799075,0.833162,0.764054
GUJARAT,60443083,41095674,31492973,23476246,28950110,17619428,0.679907,0.745444,0.608614
HARYANA,25351462,16598988,13494734,9794067,11856728,6804921,0.654755,0.725770,0.573929
HIMACHAL PRADESH,6864602,5039736,3481873,2752590,3382729,2287146,0.734163,0.790549,0.676125
JAMMU AND KASHMIR,12267013,6887227,6483906,4145536,5783107,2741691,0.561443,0.639358,0.474086
JHARKHAND,32988134,18328069,16930315,10882519,16057819,7445550,0.555596,0.642783,0.463671
KARNATAKA,61095297,40647322,30966657,22508471,30128640,18138851,0.665310,0.726862,0.602047
KERALA,33406061,28135824,16027412,13704903,17378649,14430921,0.842237,0.855091,0.830382
LADAKH,274289,180006,156756,119135,117533,60871,0.656264,0.760003,0.517906
LAKSHADWEEP,64473,52553,33123,28023,31350,24530,0.815116,0.846028,0.782456
MADHYA PRADESH,72641665,42861652,37620144,25180344,35021521,17681308,0.590042,0.669331,0.504870
MAHARASHTRA,112374333,81554290,58243056,45257584,54131277,36296706,0.725738,0.777047,0.670531
MANIPUR,2855794,1908476,1438586,1039858,1417208,868618,0.668282,0.722833,0.612908
MEGHALAYA,2966889,1785005,1491832,913879,1475057,871126,0.601642,0.612588,0.590571
MIZORAM,1097206,848175,555339,438529,541867,409646,0.773032,0.789660,0.755990
NAGALAND,1978502,1342434,1024649,723957,953853,618477,0.678510,0.706541,0.648399
ODISHA,41980846,26747327,21215646,15092454,20765200,11654873,0.637132,0.711383,0.561269
PUDUCHERRY,1247953,957309,612511,497378,635442,459931,0.767103,0.812031,0.723797
PUNJAB,27743338,18707137,14639465,10436056,13103873,8271081,0.674293,0.712871,0.631194
RAJASTHAN,68548437,38275282,35550997,23688412,32997440,14586870,0.558368,0.666322,0.442061
SIKKIM,610577,444952,323070,251269,287507,193683,0.728740,0.777754,0.673664
TAMIL NADU,72147030,51837507,36137975,28040491,36009055,23797016,0.718498,0.775929,0.660862
TELANGANA,35003674,20696778,17611633,11701729,17392041,8995049,0.591274,0.664432,0.517193
THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU,586956,411636,344061,267164,242895,144472,0.701306,0.776502,0.594792
TRIPURA,3673917,2804783,1874376,1501369,1799541,1303414,0.763431,0.800997,0.724304
UTTAR PRADESH,199812341,114397555,104480510,68234964,95331831,46162591,0.572525,0.653088,0.484231
UTTARAKHAND,10086292,6880953,5137773,3863708,4948519,3017245,0.682208,0.752020,0.609727
WEST BENGAL,91276115,61538281,46809027,33818810,44467088,27719471,0.674199,0.722485,0.623371

In [14]:
max_literate_index_male = state_totals['Male Literacy Rate'].idxmax()
max_literate_index_female = state_totals['Female Literacy Rate'].idxmax()
max_literate_index_total = state_totals['Total Literacy Rate'].idxmax()

In [26]:
print('State/Union Territory with highest Literacy Rates for Male Population :-',max_literate_index_male)
print('State/Union Territory with highest Literacy Rates for Female Population :-',max_literate_index_female)
print('State/Union Territory with highest Literacy Rates for Total Population :-',max_literate_index_total)

State/Union Territory with highest Literacy Rates for Male Population :- KERALA
State/Union Territory with highest Literacy Rates for Female Population :- KERALA
State/Union Territory with highest Literacy Rates for Total Population :- KERALA

In [32]:
census['Total-LR']=census['Literate population '] / census['Population']
census['Male-LR'] = census['Male literate population'] / census['Male population']
census['Female-LR'] = census['Female literate population '] / census['Female population']

In [33]:
census

,ROWID,Country,State lgd code,State,District lgd code,District,Sub-District lgd Code,Sub-District,ULB_RLB_Village lgd Code,ULB_RLB_Village,Rural or Urban,Households,Population,Male population,Female population,Population in the age group 0 to 6 years,Male Population in the age group 0 to 6 years,Female Population in the age group 0 to 6 years,Scheduled Caste population,Male Scheduled Caste population,Female Scheduled Caste population,Scheduled Tribe population,Male Scheduled Tribe population,Female Scheduled Tribe population,Literate population,Male literate population,Female literate population,Illiterate population,Male illiterate population,Female illiterate population,Working population,Male working population,Female Woking population,Number of main workers,Number of male main workers,Number of female main worker,Number of main workers as cultivators,Number of male main workers as cultivators,Number of female main workers as cultivators,Number of main workers as agricultural labourers,Number of male main workers as agricultural labourers,Number of female main workers as agricultural labourers,Number of main workers in the household industry,Number of male main workers in the household industry,Number of female main workers in the household industry,Number of main workers as Other workers,Number of male main workers as Other workers,Number of female main workers as Other workers,Number of marginal workers,Number of male marginal workers,Number of female marginal workers,Number of marginal workers as cultivators,Number of male marginal workers as cultivators,Number of female marginal workers as cultivators,Number of marginal workers as agricultural labourers,Number of male marginal workers as agricultural labourers,Number of female marginal workers as agricultural labourers,Number of marginal workers in the household industry,Number of male marginal workers in the household industry,Number of female marginal workers in the household industry,Number of marginal workers as Other workers,Number of male marginal workers as Other workers,Number of female marginal workers as Other workers,Number of marginal workers who worked for 3 to 6 months,Number of male marginal workers who worked for 3 to 6 months,Number of female marginal workers who worked for 3 to 6 months,Total Number of marginal workers as cultivators who worked for 3 to 6 months,Number of male marginal workers as cultivators who worked for 3 to 6 months,Number of female marginal workers as cultivators who worked for 3 to 6 months,Number of marginal workers as agricultural labour who worked for 3 to 6 months,Number of male marginal workers as agricultural labour who worked for 3 to 6 months,Number of female marginal workers as agricultural labour who worked for 3 to 6 months,Number of marginal workers in household industry who worked for 3 to 6 months,Number of male marginal workers in household industry who worked for 3 to 6 months,Number of female marginal workers in household industry who worked for 3 to 6 months,Number of marginal workers as Other workers who worked for 3 to 6 months,Number of male marginal workers as Other workers who worked for 3 to 6 months,Number of female marginal workers as Other workers who worked for 3 to 6 months,Number of marginal workers who worked for 0 to 3 months,Number of male marginal workers who worked for 0 to 3 months,Number of female marginal workers who worked for 0 to 3 months,Number of marginal workers as cultivators who worked for 0 to 3 months,Number of male marginal workers as cultivators who worked for 0 to 3 months,Number of female marginal workers as cultivators who worked for 0 to 3 months,Total nuumber of marginal workers as agricultural labour who worked for 0 to 3 months,Number of male marginal workers in agricultural labour who worked for 0 to 3 months,Number of female marginal workers as agricultural labour who worked for 0 to 3 months,Number of marginal workers in household industry who worked for 0 to 3 months,Number of male marginal workers in household industry who worked for 0 to 3 months,Number of female marginal workers in household industry who worked for 0 to 3 months,Number of marginal workers as Other workers who worked for 0 to 3 months,Number of male marginal workers as Other workers who worked for 0 to 3 months,Number of female marginal workers as Other workers who worked for 0 to 3 months,Number of Non workers,Number of male Non workers,Number of female Non workers,Source Year,YearCode,Year,Total-LR,Male-LR,Female-LR
0,585,India,24,GUJARAT,442,BHARUCH,999999,Unknown SubDistricts of India,9802612,Valia (Naldhari) (INA),Urban,1,5,5,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,5,5,0,5,5,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2011,2011,"Calendar Year (Jan - Dec), 2011",1.000000,1.000000,NaN
1,637,India,24,GUJARAT,459,SURAT,3937,Majura,802631,Surat,Urban,5,18,18,0,0,0,0,0,0,0,0,0,0,15,15,0,3,3,0,18,18,0,18,18,0,0,0,0,0,0,0,0,0,0,18,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2011,2011,"Calendar Year (Jan - Dec), 2011",0.833333,0.833333,NaN
2,1498,India,21,ODISHA,350,CUTTACK,2954,Choudwar,399316,Industrial Area (OG),Urban,2,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,2,2,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,2011,2011,"Calendar Year (Jan - Dec), 2011",1.000000,1.000000,NaN
3,2062,India,5,UTTARAKHAND,54,RUDRA PRAYAG,290,Ukhimath,800296,Kedarnath,Urban,297,612,609,3,0,0,0,26,26,0,0,0,0,601,599,2,11,10,1,604,601,3,601,598,3,1,1,0,0,0,0,0,0,0,600,597,3,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,3,3,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,0,2011,2011,"Calendar Year (Jan - Dec), 2011",0.982026,0.983580,0.666667
4,4150,India,1,JAMMU AND KASHMIR,3,BARAMULLA,39,Tangmarg,800009,Municipal Committee Gulmarg Tangmarg,Urban,77,1965,1957,8,0,0,0,12,12,0,3,3,0,1950,1942,8,15,15,0,1962,1956,6,1962,1956,6,3,3,0,0,0,0,0,0,0,1959,1953,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,2,2011,2011,"Calendar Year (Jan - Dec), 2011",0.992366,0.992335,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606673,550918,India,36,TELANGANA,698,VIKARABAD,4539,Kulkacharla,574602,Mujahidpur,Rural,1010,5344,2801,2543,667,340,327,616,306,310,1917,1038,879,2550,1639,911,2794,1162,1632,2605,1313,1292,1470,806,664,551,372,179,325,75,250,58,27,31,536,332,204,1135,507,628,215,115,100,753,297,456,36,20,16,131,75,56,1109,496,613,212,114,98,742,293,449,34,19,15,121,70,51,26,11,15,3,1,2,11,4,7,2,1,1,10,5,5,2739,1488,1251,2011,2011,"Calendar Year (Jan - Dec), 2011",0.477171,0.585148,0.358238
606674,279202,India,36,TELANGANA,698,VIKARABAD,4541,Pudur,574685,Sirgaipalle,Rural,127,651,347,304,80,47,33,0,0,0,2,2,0,381,231,150,270,116,154,174,100,74,125,70,55,54,30,24,60,30,30,1,0,1,10,10,0,49,30,19,22,13,9,9,6,3,2,1,1,16,10,6,47,28,19,21,12,9,8,5,3,2,1,1,16,10,6,2,2,0,1,1,0,1,1,0,0,0,0,0,0,0,477,247,230,2011,2011,"Calendar Year (Jan - Dec), 2011",0.585253,0.665706,0.493421
606675,45447,India,36,TELANGANA,699,KUMURAM BHEEM ASIFABAD,4318,Kagaznagar,569470,Jambuga,Rural,25,107,54,53,13,8,5,0,0,0,0,0,0,51,27,24,56,27,29,60,34,26,45,30,15,16,12,4,24,15,9,0,0,0,5,3,2,15,4,11,3,1,2,12,3,9,0,0,0,0,0,0,15,4,11,3,1,2,12,3,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,20,27,2011,2011,"Calendar Year (Jan - Dec), 2011",0.476636,0.500000,0.452830
606676,122623,India,37,LADAKH,6,KARGIL,15,Zanskar,1066,Hamiling,Rural,48,266,116,150,40,20,20,0,0,0,264,114,150,133,57,76,133,59,74,130,60,70,12,10,2,0,0,0,0,0,0,1,1,0,11,9,2,118,50,68,2,1,1,110,46,64,1,0,1,5,3,2,118,50,68,2,1,1,110,46,64,1,0,1,5,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,136,56,80,2011,2011,"Calendar Year (Jan - Dec), 2011",0.500000,0.491379,0.506667
606677,206923,India,37,LADAKH,9,LEH LADAKH,10,Leh,857,Nang,Rural,74,334,156,178,44,24,20,0,0,0,333,156,177,175,94,81,159,62,97,95,68,27,37,24,13,3,2,1,0,0,0,0,0,0,34,22,12,58,44,14,50,39,11,0,0,0,0,0,0,8,5,3,58,44,14,50,39,11,0,0,0,0,0,0,8,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,239,88,151,2011,2011,"Calendar Year (Jan - Dec), 2011",0.523952,0.602564,0.455056

In [35]:
highest_lr = census['Total-LR'].max()

highest_lrmale=census['Male-LR'].max()

highest_lrfemale=census['Female-LR'].max()

In [52]:
dist_highest_literacy = census[census['Total-LR'] == highest_lr].index.tolist()
print("District with the highest literacy rate:")
for dist in dist_highest_literacy:
    print(census.loc[dist,'District'])

District with the highest literacy rate:
BHARUCH
CUTTACK
BULANDSHAHR
LOWER SUBANSIRI
MANDI
UTTAR KASHI
SAWAI MADHOPUR
MORADABAD
UNNAO
GOPALGANJ
DHANBAD
REWA
MYSURU
SOLAN
Tarn Taran
PAURI GARHWAL
BAREILLY
WEST KAMENG
BANKURA
DEOGHAR
NEEMUCH
SHEOPUR
AMRAVATI
NAGPUR
KOLAR
UTTARA KANNADA
NORTH AND MIDDLE ANDAMAN
KULLU
LAHUL AND SPITI
BAGESHWAR
LALITPUR
COOCHBEHAR
Jhargram
GANJAM
CHIKKAMAGALURU
SOLAN
BANKA
BHOJPUR
ANUGUL
KOLAR
BASTI
KINNAUR
NAINITAL
BALLIA
JAJAPUR
KOREA
PITHORAGARH
CHAMOLI
RUDRA PRAYAG
WARDHA
SHIMLA
PAURI GARHWAL
BIKANER
CHURU
AZAMGARH
SHIMLA
NAYAGARH
VIZIANAGARAM
HARIDWAR
CHITRAKOOT
TUMAKURU
SHIMLA
PITHORAGARH
AURAIYA
DUMKA
GANJAM
BALLIA
HAPUR
PITHORAGARH
KUSHI NAGAR
VAISHALI
JAJAPUR
YAVATMAL
LAHUL AND SPITI
HARDOI
MEDINIPUR WEST
BALESHWAR
BANKURA
RAYAGADA
SHEOPUR
SHIVAMOGGA
SHIVAMOGGA
SOLAN
PAURI GARHWAL
AYODHYA
CHATRA
KHORDHA
AKOLA
MANDI
BAGESHWAR
GWALIOR
REWA
YAVATMAL
TEHRI GARHWAL
RAE BARELI
SAHARANPUR
DUMKA
MANDI
MANDI
PAURI GARHWAL
LAHUL AND SPITI
SHIMLA
RUDRA PRAYAG
DUMKA
BALAGHAT
RAISEN
RATNAGIRI
SHIVAMOGGA
KRISHNAGIRI
CHAMPAWAT
JAISALMER
JALAUN
TINSUKIA
BIRBHUM
GIRIDIH
AMRAVATI
FEROZEPUR
BHARATPUR
PILIBHIT
GANJAM
PURI
PURI
UMARIA
WARDHA
UTTARA KANNADA
CHAMBA
PITHORAGARH
KARNAL
BALLIA
YAVATMAL
BARAN
CUTTACK
CUTTACK
KANDHAMAL
DHAMTARI
BAGESHWAR
SATNA
KOPPAL
MANDI
MANDI
PAURI GARHWAL
GOLAGHAT
INDORE
KANGRA
PAURI GARHWAL
BIJNOR
REWA
KINNAUR
SAWAI MADHOPUR
JAMTARA
JAJAPUR
SATNA
PAURI GARHWAL
WARDHA
BAGESHWAR
PAURI GARHWAL
NORTH AND MIDDLE ANDAMAN
BASTI
GHAZIABAD
BANKURA
SARAIKELA KHARSAWAN
NAGPUR
RATNAGIRI
SHIMLA
DEOGHAR
CHAMPAWAT
SAMBALPUR
BENGALURU RURAL
CHAMOLI
NAGAUR
NAGAON
ANUGUL
DATIA
PANNA
LOWER SUBANSIRI
EAST SINGHBUM
BULDHANA
BHARATPUR
DHOLPUR
RAISEN
GURDASPUR
JHANSI
JORHAT
KANDHAMAL
KANGRA
BHARATPUR
BAREILLY
SOUTH ANDAMANS
AMRAVATI
SHIVAMOGGA
JALAUN
MIRZAPUR
AKOLA
HASSAN
KOLAR
MEDINIPUR WEST
KANGRA
SOLAN
BALLIA
GHAZIPUR
VAISHALI
COOCHBEHAR
DEOGHAR
ANUGUL
KINNAUR
MANDI
ALMORA
BAGESHWAR
PAURI GARHWAL
BALLIA
LOWER SUBANSIRI
ANUGUL
WARDHA
SAWAI MADHOPUR
SANT KABEER NAGAR
West Tripura
CUTTACK
YADGIR
CHAMBA
KANDHAMAL
NARSINGHPUR
RATLAM
MANDYA
NORTH AND MIDDLE ANDAMAN
ALMORA
BANKA
LOWER SUBANSIRI
NAGAON
SATNA
CHANDRAPUR
GONDIA
KOLAR
SHIMLA
PITHORAGARH
Kasganj
MADHEPURA
Jhargram
RAISEN
AMRAVATI
WARDHA
LOWER SUBANSIRI
RAE BARELI
KHAGARIA
SITAMARHI
LOWER SUBANSIRI
LATEHAR
SIDHI
MANDI
SATNA
DAVANGERE
MANDI
GORAKHPUR
MAHARAJGANJ
KHORDHA
AKOLA
BENGALURU RURAL
GURDASPUR
DEHRADUN
HARIDWAR
BANKURA
BALESHWAR
BAGESHWAR
CHAMOLI
CHAMOLI
GONDA
VARANASI
MEDINIPUR EAST
NAGPUR
BAGESHWAR
MANDI
PAURI GARHWAL
PALAMU
KODAGU
KUPWARA
HAMIRPUR
PATIALA
PAURI GARHWAL
BASTI
MAYURBHANJ
SUNDARGARH
SRIKAKULAM
KANGRA
MAYURBHANJ
KACHCHH
MEDINIPUR EAST
EAST GARO HILLS
LAKHIMPUR
Biswanath
BALAGHAT
CHIKKAMAGALURU
CHAMBA
SHIMLA
SHIMLA
RAMPUR
BALESHWAR
REWA
RAE BARELI
SANT KABEER NAGAR
DEOGHAR
JAMTARA
KENDRAPARA
NORTH AND MIDDLE ANDAMAN
PITHORAGARH
UTTAR KASHI
SANT KABEER NAGAR
BALAGHAT
KATNI
TIKAMGARH
VIDISHA
NAMAKKAL
SHAHJAHANPUR
LOWER SUBANSIRI
BARPETA
ANUGUL
KOLAR
BAGESHWAR
PAURI GARHWAL
BHARATPUR
DUMKA
CHHINDWARA
BASTI
KODERMA
CUTTACK
MAYURBHANJ
MANDI
CHAMPAWAT
DEHRADUN
SIDDHARTH NAGAR
DINAJPUR DAKSHIN
SATNA
LAHUL AND SPITI
ALMORA
DIBRUGARH
KAMRUP
PAURI GARHWAL
DEWAS
WARDHA
BALESHWAR
KHUNTI
BHAVNAGAR
CHAMOLI
PILIBHIT
LOWER SUBANSIRI
CHATRA
KATNI
YAVATMAL
CHAMBA
KINNAUR
CHANDAULI
KENDRAPARA
AZAMGARH
TUMAKURU
SITAMARHI
RAJNANDGAON
BALAGHAT
SHEOPUR
LAKSHADWEEP DISTRICT
ANUGUL
BHANDARA
KANPUR NAGAR
SAMBHAL
ROHTAS
MEDINIPUR WEST
GIRIDIH
WASHIM
JAMMU
GHAZIPUR
GODDA
NORTH AND MIDDLE ANDAMAN
S.A.S Nagar
CHAMOLI
KAIMUR (BHABUA)
BANKURA
CHAMPAWAT
PAURI GARHWAL
SATNA
CHURACHANDPUR
BAGESHWAR
CHAMOLI
HANUMANGARH
MIRZAPUR
SAHARANPUR
KHORDHA
KINNAUR
HARIDWAR
MAHOBA
PAPUM PARE
SHIVPURI
WEST GODAVARI
BULANDSHAHR
DEORIA
MAU
PURI
CHANDRAPUR
WARDHA
GHAZIPUR
CACHAR
HOSHIARPUR
PAURI GARHWAL
ALWAR
NAGPUR
BASTI
BUDAUN
SHIMLA
ALMORA
CHAMOLI
KARIMGANJ
ANUGUL
PAURI GARHWAL
GANGANAGAR
AURANGABAD
SEHORE
JAISALMER
JHANSI
HAMIRPUR
PAURI GARHWAL
KOTA
BALESHWAR
HASSAN
BUNDI
Jhargram
ANUGUL
BALESHWAR
MANDI
PITHORAGARH
GANJAM
RUDRA PRAYAG
NADIA
BHIND
SATNA
GIR SOMNATH
SOLAN
ALMORA
SAWAI MADHOPUR
BAREILLY
NORTH GARO HILLS
MAYURBHANJ
PURI
HASSAN
LAHUL AND SPITI
MATHURA
PAKUR
KANGRA
SHIMLA
JALANDHAR
PILIBHIT
EAST KHASI HILLS
MEDINIPUR WEST
NANDED
PILIBHIT
BALAGHAT
ALMORA
MANDI
SOLAN
BIJNOR
GHAZIPUR
RAMPUR
DAMOH
BAGESHWAR
CHAMPAWAT
EAST KHASI HILLS
SONEPUR
BALRAMPUR
UTTAR KASHI
HARIDWAR
Jhargram
BHANDARA
CHIKKABALLAPURA
GHAZIPUR
GADAG
BAGESHWAR
BAGESHWAR
BASTI
DEORIA
KHERI
MEERUT
DARBHANGA
LOWER SUBANSIRI
JORHAT
PITHORAGARH
PITHORAGARH
AGRA
BALAGHAT
REWA
NAGPUR
PARBHANI
BIJNOR
JALAUN
JAGATSINGHAPUR
PILIBHIT
DHAR
MANDI
BHARATPUR
MIRZAPUR
SAHARANPUR
HAPUR
BALESHWAR
PAURI GARHWAL
LALITPUR
ANUGUL
BALAGHAT
HASSAN
FATEHPUR
UTTAR KASHI
KAIMUR (BHABUA)
HASSAN
CHHINDWARA
KHARGONE
VIRUDHUNAGAR
ALMORA
GORAKHPUR
MEDINIPUR WEST
SATNA
LOWER SUBANSIRI
NAGPUR
CHIKKAMAGALURU
LAHUL AND SPITI
MANDI
ALMORA
PRATAPGARH
SHIMLA
KAMRUP METRO
AMRAVATI
NAGPUR
NAGPUR
BAGESHWAR
MEERUT
SHEOPUR
KOKRAJHAR
BIJNOR
AKOLA
JALANDHAR
BIJNOR
SIRSA
KOTA
JALAUN
DEOGHAR
RAISEN
MANDI
HAMIRPUR
KINNAUR
UTTAR KASHI
BASTI
SHAHJAHANPUR
RAMPUR
BALESHWAR
MAYURBHANJ
YAVATMAL
BOUDH
UMARIA
BASTI
KAIMUR (BHABUA)
MANDSAUR
BASTI
BALAGHAT
REWA
LAKSHADWEEP DISTRICT
GURDASPUR
BAGESHWAR
BAGESHWAR
CHAMPAWAT
TEHRI GARHWAL
SULTANPUR
MEDINIPUR WEST
SAHEBGANJ
GARIYABAND
HOSHANGABAD
SOLAN
LOWER SUBANSIRI
JORHAT
DINAJPUR DAKSHIN
RAISEN
REWA
NAGPUR
SIDDIPET
JAJAPUR
ASHOKNAGAR
SHIMLA
CHAMOLI
ANUGUL
REWA
SHIMLA
SHIMLA
SHIMLA
CHITTORGARH
MIRZAPUR
DIBANG VALLEY
UTTARA KANNADA
HOSHIARPUR
NAINITAL
BASTI
MANDI
LOWER SUBANSIRI
KANGRA
SOLAN
GOLAGHAT
BANKURA
KHORDHA
NICOBARS
SHIMLA
SOLAN
BIJNOR
WEST DISTRICT
EAST KHASI HILLS
SIVASAGAR
BALESHWAR
YAVATMAL
DAVANGERE
BAGESHWAR
GORAKHPUR
EAST KHASI HILLS
ANUGUL
SINGRAULI
ALMORA
MORADABAD
AURANGABAD
BAGESHWAR
CACHAR
DHENKANAL
WARDHA
MANDI
NAINITAL
BHILWARA
SAMBALPUR
ALMORA
MYSURU
AJMER
JAUNPUR
PAKKE KESSANG
BIRBHUM
TEHRI GARHWAL
SHAHJAHANPUR
UTTARA KANNADA
SOLAN
PURBI CHAMPARAN
KENDRAPARA
PAURI GARHWAL
Jhargram
CHATRA
DHANBAD
DHENKANAL
SIDHI
OSMANABAD
PAURI GARHWAL
CHANDAULI
CHAMARAJANAGARA
TUMAKURU
ANUGUL
MANDI
SONEPUR
BALAGHAT
JAUNPUR
SANT KABEER NAGAR
HOSHIARPUR
KAMRUP
MEDINIPUR WEST
NAYAGARH
JABALPUR
RAJGARH
MANDI
MATHURA
CHHINDWARA
BENGALURU RURAL
BILASPUR
CHAMBA
BHAGALPUR
JORHAT
SHIVPURI
AMRAVATI
KANGRA
UTTAR KASHI
GOLAGHAT
MARIGAON
WARDHA
KOLAR
TUMAKURU
BIJNOR
KAIMUR (BHABUA)
SOLAN
UTTAR KASHI
PILIBHIT
SATNA
PARBHANI
UNA
PAURI GARHWAL
AZAMGARH
BASTI
BIJNOR
NARSINGHPUR
SATNA
RAIGAD
KANGRA
HARDOI
MIRZAPUR
NAGPUR
HASSAN
MAYURBHANJ
REWA
PATHANKOT
UTTAR KASHI
PRATAPGARH
CUTTACK
DHENKANAL
WARDHA
SHIMLA
UNA
BUDAUN
CHANDAULI
HAPUR
UTTAR KASHI
AZAMGARH
FARRUKHABAD
HAMIRPUR
PURNIA
GWALIOR
BULDHANA
CHIKKAMAGALURU
SAHARSA
BALESHWAR
GAJAPATI
NAYAGARH
CHITRADURGA
KOLAR
PAURI GARHWAL
PITHORAGARH
MEDINIPUR EAST
JAMMU
GURDASPUR
ALMORA
SAHARANPUR
ROHTAS
BARPETA
DHEMAJI
CHIKKAMAGALURU
SAWAI MADHOPUR
JALAUN
MUZAFFARNAGAR
SULTANPUR
RAJNANDGAON
CHENGALPATTU
SOLAN
CHAMPAWAT
HAPUR
BETUL
CHAMOLI
PAURI GARHWAL
MAU
CHAMBA
PAURI GARHWAL
PITHORAGARH
DHEMAJI
DIBRUGARH
MAYURBHANJ
NAYAGARH
JANJGIR-CHAMPA
HOSHIARPUR
KURUKSHETRA
MAYURBHANJ
BIJAPUR
KAPURTHALA
BAGESHWAR
NUH
PILIBHIT
RAISEN
TUMAKURU
Biswanath
KANGRA
SOLAN
CHANDAULI
CHANGLANG
SONEPUR
DEHRADUN
BANKURA
MALDAH
LAHUL AND SPITI
BAGESHWAR
BAGESHWAR
BIJNOR
GHAZIPUR
BANKURA
VIDISHA
SHIMLA
MANDI
MANDI
WEST JAINTIA HILLS
ANUGUL
SOLAN
DEOGARH
CHANDRAPUR
CHAMOLI
AYODHYA
GHAZIPUR
RAE BARELI
BETUL
BENGALURU RURAL
CHIKKAMAGALURU
CHITRADURGA
KINNAUR
CHAMOLI
KODERMA
KORAPUT
AKOLA
AKOLA
SOLAN
JHANSI
GODDA
MAYURBHANJ
SHIMLA
HANUMANGARH
MEDINIPUR WEST
NAGPUR
NORTH AND MIDDLE ANDAMAN
PAURI GARHWAL
GANJAM
KHORDHA
KULLU
MALDAH
WARDHA
KARBI ANGLONG
KARIMGANJ
BANKURA
GANJAM
MAYURBHANJ
MAYURBHANJ
NORTH AND MIDDLE ANDAMAN
NORTH AND MIDDLE ANDAMAN
SHIMLA
SOLAN
MIRZAPUR
UNNAO
BALAGHAT
SHIVAMOGGA
SOUTH DISTRICT
DINAJPUR DAKSHIN
BALAGHAT
SATNA
GIR SOMNATH
CHURU
GANGANAGAR
MIRZAPUR
SUNDARGARH
REWA
BHARATPUR
LONGDING
DEOGARH
BAHRAICH
KOKRAJHAR
MEDINIPUR EAST
CHHINDWARA
NARSINGHPUR
HAMIRPUR
UDAM SINGH NAGAR
GORAKHPUR
SAMBALPUR
PAURI GARHWAL
SIDDHARTH NAGAR
LOWER SUBANSIRI
ANJAW
Jhargram
CHIKKAMAGALURU
BASTI
SANT KABEER NAGAR
GODDA
KOLAR
TEHRI GARHWAL
AMBEDKAR NAGAR
MAHOBA
REWA
HASSAN
KANGRA
SOLAN
NAINITAL
PASHCHIM CHAMPARAN
MAYURBHANJ
NAGAON
BHADRAK
BIJAPUR
KANGRA
CHAMPAWAT
SHRAVASTI
BALAGHAT
LAHUL AND SPITI
HOSHIARPUR
ALMORA
MEERUT
CHIRANG
DHENKANAL
SHIVPURI
AMRAVATI
HASSAN
BILASPUR
UNA
SAWAI MADHOPUR
KARBI ANGLONG
BARGARH
NANDED
HASSAN
CHAMPAWAT
SONITPUR
SAHEBGANJ
GANJAM
ALMORA
GHAZIPUR
SATNA
SOLAN
ALMORA
GANGANAGAR
KINNAUR
HARIDWAR
JAISALMER
GWALIOR
VIZIANAGARAM
PAURI GARHWAL
GODDA
NAYAGARH
RAISEN
CHANDRAPUR
RATNAGIRI
MYSURU
DEHRADUN
GHAZIPUR
SAHARANPUR
SANT KABEER NAGAR
CHANDAULI
WEST KAMENG
Jhargram
NAGPUR
KINNAUR
PAURI GARHWAL
PURULIA
DEOGHAR
BALESHWAR
GIR SOMNATH
CHITTOOR
KOPPAL
BAGESHWAR
PAURI GARHWAL
PITHORAGARH
JHANSI
MUZAFFARPUR
LAHUL AND SPITI
CHAMOLI
MORADABAD
EAST SINGHBUM
DHENKANAL
RAICHUR
LAHUL AND SPITI
SHIMLA
RUDRA PRAYAG
BASTI
JAUNPUR
SAMBALPUR
AMBEDKAR NAGAR
MIRZAPUR
MUZAFFARPUR
BILASPUR
MANDI
SHIMLA
PAURI GARHWAL
HANUMANGARH
SAGAR
SHIMLA
ALMORA
BASTI
MAU
ANUGUL
DHENKANAL
AKOLA
SOUTH ANDAMANS
SOLAN
MAYURBHANJ
CHAMPAWAT
RUDRA PRAYAG
PASHCHIM CHAMPARAN
LOWER SUBANSIRI
GUNA
KATNI
CHANDRAPUR
MUNGER
BANKURA
BENGALURU RURAL
SAMASTIPUR
SAMBALPUR
DEWAS
SHIMLA
PATIALA
BIKANER
Unknown Districts Of India
EAST GODAVARI
BALLARI
KINNAUR
SOLAN
BASTI
BASTI
PILIBHIT
BIRBHUM
ALMORA
CHURU
AZAMGARH
BALLIA
KHERI
EAST SINGHBUM
KHARGONE
SAGAR
JALANDHAR
CHAMPAWAT
SAHARANPUR
SAGAR
CHAMBA
CHAMPAWAT
PRATAPGARH
JHANSI
EAST SINGHBUM
SARAIKELA KHARSAWAN
CUTTACK
GONDIA
PAURI GARHWAL
PURBI CHAMPARAN
CHAMPAWAT
KACHCHH
BHANDARA
TUMAKURU
ALMORA
BAGESHWAR
DEORIA
LUCKNOW
SONBHADRA
BANKURA
BULDHANA
KODAGU
SOUTH ANDAMANS
BASTI
CHANDAULI
PURULIA
HAZARIBAGH
SHIVPURI
NORTH AND MIDDLE ANDAMAN
PURI
THANJAVUR
SHIMLA
HANUMANGARH
BASTI
BULANDSHAHR
JAJAPUR
WARDHA
HASSAN
SANGAREDDY
BHARATPUR
DHENKANAL
NARSINGHPUR
SATNA
CHAMBA
PAURI GARHWAL
ANANTAPUR
THIRUVARUR
BIJNOR
SHAMLI
CHANDRAPUR
NORTH AND MIDDLE ANDAMAN
SOLAN
ALMORA
BAGESHWAR
KANPUR DEHAT
CHATRA
DEOGHAR
CHITRADURGA
SHIMLA
PAURI GARHWAL
TAWANG
WEST KAMENG
KHORDHA
SAMBALPUR
BALAGHAT
GANGANAGAR
BASTI
BHANDARA
UNA
CHAMPAWAT
BIRBHUM
KODERMA
BALESHWAR
AMRAVATI
GADCHIROLI
NANDED
PAURI GARHWAL
PITHORAGARH
ZUNHEBOTO
VIDISHA
WARDHA
Nirmal
PAURI GARHWAL
MANDI
BALLIA
LOWER SUBANSIRI
DAVANGERE
HAMIRPUR
SHIMLA
BARAN
KRA DAADI
WARDHA
SHIMLA
BHARATPUR
SHAHJAHANPUR
CHANGLANG
CHATRA
ALMORA
PAURI GARHWAL
HANUMANGARH
KOTA
AZAMGARH
LAKHIMPUR
KINNAUR
MANDI
SHIMLA
BARAN
MAYURBHANJ
REWA
SOLAN
CHAMPAWAT
PASHCHIM CHAMPARAN
BANKURA
MEDINIPUR WEST
RAISEN
GIR SOMNATH
BULDHANA
SPSR NELLORE
ALMORA
CHANGLANG
TINSUKIA
GARHWA
BHOPAL
DEVBHUMI DWARKA
ALMORA
EAST SINGHBUM
KANGRA
KULLU
UNA
PITHORAGARH
BIKANER
WOKHA
MEDINIPUR WEST
UTTARA KANNADA
KATHUA
AZAMGARH
BALAGHAT
BILASPUR
CHAMOLI
SONIPAT
PURNIA
WEST JAINTIA HILLS
BALAGHAT
MANDI
SHIVAMOGGA
UTTARA KANNADA
LAHUL AND SPITI
AZAMGARH
PASHCHIM CHAMPARAN
CHAMOLI
MAYURBHANJ
SOLAN
SOLAN
ALWAR
KAIMUR (BHABUA)
HAZARIBAGH
BALAGHAT

In [47]:
dist_highest_literacy_male = census[census['Male-LR'] == highest_lrmale].index.tolist()
print("District with the highest male literacy rate:")
for dist in dist_highest_literacy_male:
    print(census.loc[dist,'District'])

District with the highest male literacy rate:
BHARUCH
CUTTACK
UTTAR KASHI
PAURI GARHWAL
SHIMLA
BULANDSHAHR
LOWER SUBANSIRI
MANDI
MANDI
SHIMLA
PAURI GARHWAL
PAURI GARHWAL
UTTAR KASHI
UTTAR KASHI
SAWAI MADHOPUR
MORADABAD
UNNAO
GOPALGANJ
DHANBAD
DUMKA
JAGATSINGHAPUR
REWA
WARDHA
MYSURU
SHIVAMOGGA
SHIVAMOGGA
SOLAN
Tarn Taran
BAREILLY
DEORIA
GHAZIPUR
GORAKHPUR
WEST KAMENG
MARIGAON
BANKURA
DEOGHAR
DEOGHAR
NEEMUCH
SHEOPUR
AMRAVATI
NAGPUR
RAIGAD
KOLAR
UTTARA KANNADA
NORTH AND MIDDLE ANDAMAN
KULLU
LAHUL AND SPITI
SOLAN
SOLAN
BAGESHWAR
PITHORAGARH
LALITPUR
COOCHBEHAR
Jhargram
GANJAM
AKOLA
CHIKKAMAGALURU
SOLAN
SOLAN
PITHORAGARH
MAU
BANKA
BHOJPUR
PAKUR
ANUGUL
RAYAGADA
BHANDARA
CHITRADURGA
KOLAR
BASTI
KINNAUR
KINNAUR
NAINITAL
PAURI GARHWAL
PAURI GARHWAL
BALLIA
JAJAPUR
KOREA
PITHORAGARH
BILASPUR
SHIMLA
CHAMOLI
PAURI GARHWAL
RUDRA PRAYAG
BALAGHAT
CHATRA
BALESHWAR
WARDHA
SHIMLA
SHIMLA
ALMORA
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
BIKANER
CHURU
AZAMGARH
BALLIA
KHORDHA
MAYURBHANJ
NAGPUR
HASSAN
HASSAN
PUDUKKOTTAI
MANDI
SHIMLA
SOLAN
ALMORA
JAUNPUR
PRAYAGRAJ
DHENKANAL
NAYAGARH
VIZIANAGARAM
HASSAN
UTTARA KANNADA
NORTH AND MIDDLE ANDAMAN
MANDI
SOLAN
HARIDWAR
PITHORAGARH
HANUMANGARH
CHITRAKOOT
TUMAKURU
NAGAPATTINAM
SHIMLA
PITHORAGARH
AURAIYA
GHAZIPUR
SHAHJAHANPUR
DUMKA
ANUGUL
GANJAM
RAIGAD
TUMAKURU
KANGRA
ALMORA
PAURI GARHWAL
HANUMANGARH
BALLIA
HAPUR
MANDYA
SHIVAMOGGA
TUMAKURU
CHAMBA
SOLAN
SOLAN
CHAMOLI
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
KUSHI NAGAR
VARANASI
VAISHALI
JAJAPUR
WARDHA
YAVATMAL
SRIKAKULAM
BENGALURU RURAL
HAMIRPUR
LAHUL AND SPITI
HARDOI
MIRZAPUR
KAKCHING
MEDINIPUR WEST
Jhargram
BALESHWAR
SONEPUR
REWA
ADILABAD
MANDI
SHIMLA
SHIMLA
SOLAN
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
GANGANAGAR
TONK
BASTI
GHAZIPUR
BANKURA
GIRIDIH
RAYAGADA
SHEOPUR
SHIVAMOGGA
SHIVAMOGGA
SOLAN
PAURI GARHWAL
BASTI
AYODHYA
MAU
CHATRA
DEOGHAR
KHORDHA
RAISEN
AKOLA
CHAMARAJANAGARA
MANDI
SHIMLA
BAGESHWAR
AZAMGARH
GWALIOR
NARSINGHPUR
REWA
YAVATMAL
SOLAN
TEHRI GARHWAL
RAE BARELI
SAHARANPUR
Jhargram
DUMKA
TUMAKURU
KANGRA
MANDI
MANDI
SOLAN
CHAMOLI
CHAMPAWAT
PAURI GARHWAL
JAIPUR
BALLIA
BASTI
GANJAM
KANDHAMAL
NEEMUCH
JAMMU
LAHUL AND SPITI
SHIMLA
ALMORA
RUDRA PRAYAG
JAUNPUR
JAUNPUR
MEDINIPUR WEST
DUMKA
KANDHAMAL
BALAGHAT
HARDA
RAISEN
RATNAGIRI
SHIVAMOGGA
KRISHNAGIRI
KANGRA
MANDI
CHAMPAWAT
PAURI GARHWAL
JAISALMER
BALLIA
KAIMUR (BHABUA)
DIMA HASAO
MEDINIPUR EAST
GODDA
JAJAPUR
AKOLA
HASSAN
HAMIRPUR
KANGRA
PAURI GARHWAL
JALAUN
MIRZAPUR
TINSUKIA
DIBANG VALLEY
BIRBHUM
GIRIDIH
GIRIDIH
NARSINGHPUR
REWA
SAGAR
AMRAVATI
YAVATMAL
MANDI
FEROZEPUR
BHARATPUR
DAUSA
MIRZAPUR
PILIBHIT
WEST KAMENG
GANJAM
PURI
PURI
NARSINGHPUR
UMARIA
WARDHA
UTTARA KANNADA
KANCHIPURAM
CHAMBA
LAHUL AND SPITI
CHAMPAWAT
PITHORAGARH
KARNAL
BALLIA
NAGPUR
YAVATMAL
HAMIRPUR
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
BARAN
HANUMANGARH
SHAHJAHANPUR
SOUTH WEST KHASI HILLS
CUTTACK
CHITTOOR
MANDYA
KANGRA
KANGRA
MANDI
SOLAN
PITHORAGARH
RUDRA PRAYAG
GORAKHPUR
BIRBHUM
DEOGHAR
CUTTACK
KANDHAMAL
DHAMTARI
LAHUL AND SPITI
SOLAN
BAGESHWAR
PAURI GARHWAL
PAURI GARHWAL
PRAYAGRAJ
SATNA
KOPPAL
MANDI
MANDI
MANDI
BAGESHWAR
PAURI GARHWAL
RUDRA PRAYAG
SAHARANPUR
GOLAGHAT
DHENKANAL
INDORE
PAURI GARHWAL
KANGRA
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
BIJNOR
REWA
KINNAUR
SOLAN
BIKANER
GANGANAGAR
SAWAI MADHOPUR
JAMTARA
BALESHWAR
JAJAPUR
REWA
SATNA
KANGRA
CHAMOLI
AJMER
BIJNOR
BANKA
LOWER SIANG
DINAJPUR DAKSHIN
AMRAVATI
WARDHA
BAGESHWAR
MANDI
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
GORAKHPUR
EAST KAMENG
LOWER DIBANG VALLEY
KHORDHA
REWA
KOLAR
NORTH AND MIDDLE ANDAMAN
KINNAUR
KISHANGANJ
KACHCHH
BASTI
GHAZIABAD
GHAZIPUR
KUSHI NAGAR
BEGUSARAI
BANKURA
SARAIKELA KHARSAWAN
GANGANAGAR
DEWAS
REWA
NAGPUR
RATNAGIRI
SHIMLA
RUDRA PRAYAG
GOLAGHAT
DEOGHAR
CHAMPAWAT
SAMBALPUR
HARIDWAR
MANDI
YAVATMAL
BALLARI
HASSAN
LAHUL AND SPITI
SOLAN
ALMORA
PAURI GARHWAL
PAURI GARHWAL
MAHOBA
NAYAGARH
SAGAR
BENGALURU RURAL
MANDI
CHAMOLI
PAURI GARHWAL
NAGAUR
JALAUN
MATHURA
NAGAON
DINAJPUR DAKSHIN
DATIA
PANNA
NAGPUR
WARDHA
JHANSI
LOWER DIBANG VALLEY
LOWER SUBANSIRI
EAST SINGHBUM
BULDHANA
BULDHANA
RATNAGIRI
Y.S.R.
BAGALKOTE
TUMAKURU
KULLU
HOSHIARPUR
AJMER
BHARATPUR
DHOLPUR
AZAMGARH
KAIMUR (BHABUA)
RAISEN
RATLAM
TUMAKURU
GURDASPUR
PAURI GARHWAL
PAURI GARHWAL
SAWAI MADHOPUR
PRAYAGRAJ
AZAMGARH
CHANDAULI
JHANSI
JORHAT
MEDINIPUR WEST
GIRIDIH
KANDHAMAL
CHIKKABALLAPURA
KANGRA
MANDI
RUPNAGAR
NAINITAL
PAURI GARHWAL
BHARATPUR
BALESHWAR
SOUTH ANDAMANS
HAMIRPUR
MANDI
SHIMLA
HANUMANGARH
PAURI GARHWAL
HANUMANGARH
HAMIRPUR
MAU
SONBHADRA
DIBANG VALLEY
GAJAPATI
KALAHANDI
AMRAVATI
SHIVAMOGGA
PAURI GARHWAL
PITHORAGARH
BASTI
GHAZIPUR
JALAUN
AMROHA
MIRZAPUR
UNNAO
AKOLA
BENGALURU RURAL
HASSAN
KOLAR
CHAMPAWAT
DIBANG VALLEY
MEDINIPUR WEST
Jhargram
DHANBAD
GAJAPATI
JAJAPUR
BETUL
SAGAR
VIDISHA
SHIVAMOGGA
KANGRA
LAHUL AND SPITI
LAHUL AND SPITI
SOLAN
PITHORAGARH
BALLIA
GHAZIPUR
GAYA
VAISHALI
COOCHBEHAR
CHARAIDEO
BIRBHUM
MURSHIDABAD
CHATRA
DEOGHAR
ANUGUL
BALESHWAR
KINNAUR
MANDI
SOLAN
SOLAN
ALMORA
BAGESHWAR
BAGESHWAR
PAURI GARHWAL
PITHORAGARH
RUDRA PRAYAG
HANUMANGARH
BALLIA
LOWER SUBANSIRI
ANUGUL
DUMKA
BALESHWAR
WARDHA
YAVATMAL
UTTARA KANNADA
SOLAN
SOLAN
SAWAI MADHOPUR
DEORIA
HAMIRPUR
PILIBHIT
SANT KABEER NAGAR
TIRAP
West Tripura
BANKURA
MEDINIPUR EAST
BALESHWAR
CUTTACK
SATNA
YADGIR
CHAMBA
ALMORA
AZAMGARH
MAU
KANDHAMAL
NAYAGARH
NARSINGHPUR
RATLAM
MANDYA
NORTH AND MIDDLE ANDAMAN
CHAMBA
LAHUL AND SPITI
LUDHIANA
ALMORA
ALMORA
CHAMOLI
PAURI GARHWAL
BANKA
EAST KAMENG
LOWER SUBANSIRI
NAGAON
MEDINIPUR WEST
HAZARIBAGH
SATNA
MAYURBHANJ
CHANDRAPUR
GONDIA
KOLAR
NAINITAL
Mulugu
HAMIRPUR
SHIMLA
JALANDHAR
PITHORAGARH
CHITTORGARH
BASTI
JAUNPUR
Kasganj
KATIHAR
MADHEPURA
PATNA
Jhargram
DEOGHAR
PURI
RAISEN
AMRAVATI
WARDHA
ANANTAPUR
JAYASHANKAR BHUPALAPALLY
SHIMLA
ALMORA
GHAZIPUR
LOWER SUBANSIRI
RAE BARELI
KHAGARIA
SITAMARHI
LOWER SUBANSIRI
MEDINIPUR WEST
LATEHAR
REWA
SIDHI
MANDI
KAPURTHALA
PAURI GARHWAL
HANUMANGARH
KAIMUR (BHABUA)
DUMKA
SATNA
DAVANGERE
MANDI
KAPURTHALA
PAURI GARHWAL
PITHORAGARH
GORAKHPUR
MAHARAJGANJ
GIRIDIH
GODDA
GODDA
KHORDHA
AKOLA
BHANDARA
BENGALURU RURAL
TIRUCHIRAPPALLI
SOLAN
GURDASPUR
DEHRADUN
HARIDWAR
PAURI GARHWAL
PITHORAGARH
JAISALMER
AMROHA
LOWER SUBANSIRI
BANKURA
BALESHWAR
REWA
UMARIA
KANGRA
SOLAN
ALMORA
BAGESHWAR
CHAMOLI
CHAMOLI
PAURI GARHWAL
PAURI GARHWAL
HANUMANGARH
GONDA
VARANASI
BANKURA
MEDINIPUR EAST
BALESHWAR
NAGPUR
MANDYA
BAGESHWAR
KANGRA
MANDI
PAURI GARHWAL
RUDRA PRAYAG
MEERUT
PALAMU
MORENA
KODAGU
KUPWARA
HAMIRPUR
MANDI
PATIALA
RUPNAGAR
CHAMPAWAT
HARIDWAR
PAURI GARHWAL
PAURI GARHWAL
TEHRI GARHWAL
BASTI
JAUNPUR
SULTANPUR
DINAJPUR DAKSHIN
EAST SINGHBUM
PAKUR
SAMBA
KINNAUR
PAURI GARHWAL
PAURI GARHWAL
CHANDAULI
MAYURBHANJ
SUNDARGARH
SRIKAKULAM
HAMIRPUR
KANGRA
HARIDWAR
AMBEDKAR NAGAR
BHAGALPUR
MAYURBHANJ
SONEPUR
KACHCHH
LAHUL AND SPITI
PAURI GARHWAL
PITHORAGARH
GANGANAGAR
GORAKHPUR
KISHANGANJ
MEDINIPUR EAST
KANDHAMAL
UTTARA KANNADA
KANGRA
ALMORA
CHAMOLI
PAURI GARHWAL
PITHORAGARH
EAST GARO HILLS
LAKHIMPUR
Biswanath
MEDINIPUR WEST
BALAGHAT
CHIKKAMAGALURU
CHAMBA
SHIMLA
SHIMLA
SOLAN
AZAMGARH
CHAMPAWAT
UTTAR KASHI
AZAMGARH
RAMPUR
DEOGHAR
BALESHWAR
REWA
HOSHIARPUR
PAURI GARHWAL
HAMIRPUR
RAE BARELI
SANT KABEER NAGAR
BANKURA
MEDINIPUR WEST
Jhargram
DEOGHAR
JAMTARA
KENDRAPARA
HAMIRPUR
NORTH AND MIDDLE ANDAMAN
PITHORAGARH
UTTAR KASHI
AZAMGARH
AZAMGARH
RAE BARELI
SANT KABEER NAGAR
EAST SINGHBUM
JAMTARA
ANUGUL
BALAGHAT
KATNI
TIKAMGARH
VIDISHA
JUNAGADH
NAGPUR
WARDHA
HASSAN
NAMAKKAL
TEHRI GARHWAL
GORAKHPUR
SHAHJAHANPUR
LOWER SUBANSIRI
BARPETA
ANUGUL
SOLAN
BAGESHWAR
PAURI GARHWAL
BHARATPUR
GANGANAGAR
CHITRAKOOT
AMROHA
MEDINIPUR EAST
Unknown Districts Of India
DUMKA
GIRIDIH
CHHINDWARA
SATNA
TIKAMGARH
CHANDRAPUR
ALMORA
NAINITAL
HANUMANGARH
AMBEDKAR NAGAR
BASTI
JAUNPUR
MEDINIPUR WEST
KODERMA
CUTTACK
KANDHAMAL
MAYURBHANJ
SHIVAMOGGA
MANDI
CHAMPAWAT
DEHRADUN
PAURI GARHWAL
PITHORAGARH
LOWER SUBANSIRI
SIDDHARTH NAGAR
DINAJPUR DAKSHIN
ASHOKNAGAR
SATNA
LAHUL AND SPITI
MANDI
MANDI
UNA
ALMORA
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
DIBRUGARH
KAMRUP
PAURI GARHWAL
RAJNANDGAON
DEWAS
WARDHA
MANDI
ALMORA
TEHRI GARHWAL
GAUTAM BUDDHA NAGAR
BASTI
JAJAPUR
BALESHWAR
KHUNTI
KHARGONE
REWA
BHAVNAGAR
CHANDAULI
HAMIRPUR
MANDI
UNA
CHAMOLI
PRAYAGRAJ
PILIBHIT
LOWER SUBANSIRI
CHATRA
BALESHWAR
BALESHWAR
JABALPUR
KATNI
NAGPUR
YAVATMAL
PUDUKKOTTAI
KINNAUR
SOLAN
RAJSAMAND
CHANDAULI
KENDRAPARA
AZAMGARH
RAISEN
REWA
HASSAN
TUMAKURU
SOLAN
SOLAN
SOLAN
BAGESHWAR
PRAYAGRAJ
SITAMARHI
PALAMU
RAJNANDGAON
BALAGHAT
SHEOPUR
LAKSHADWEEP DISTRICT
BILASPUR
SHIMLA
HOSHIARPUR
PITHORAGARH
RUDRA PRAYAG
JAUNPUR
JAUNPUR
EAST SINGHBUM
ANUGUL
MALKANGIRI
BHANDARA
PATHANKOT
ALMORA
ALMORA
KANPUR NAGAR
MAU
SIDDHARTH NAGAR
SAMBHAL
ROHTAS
MEDINIPUR WEST
GIRIDIH
KANDHAMAL
NAGPUR
WASHIM
JAMMU
MANDI
SHIMLA
DEHRADUN
RUDRA PRAYAG
HANUMANGARH
GHAZIPUR
GODDA
NORTH AND MIDDLE ANDAMAN
SOLAN
S.A.S Nagar
CHAMOLI
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
RUDRA PRAYAG
SHAHJAHANPUR
BANKA
KAIMUR (BHABUA)
BANKURA
KANDHAMAL
SHAJAPUR
ALMORA
CHAMPAWAT
PAURI GARHWAL
PAURI GARHWAL
GANGANAGAR
AZAMGARH
BARPETA
MEDINIPUR WEST
MEDINIPUR WEST
DUMKA
SATNA
MANDI
SHIMLA
HARIDWAR
BULANDSHAHR
JAUNPUR
CHURACHANDPUR
KORAPUT
PURI
CHHINDWARA
HASSAN
MANDI
BAGESHWAR
CHAMOLI
PAURI GARHWAL
HANUMANGARH
GHAZIPUR
MIRZAPUR
SAHARANPUR
KHORDHA
REWA
CHANDRAPUR
KINNAUR
HARIDWAR
AZAMGARH
MAHOBA
BANKA
DEOGHAR
NEEMUCH
HAMIRPUR
ALMORA
CHAMPAWAT
PAURI GARHWAL
TEHRI GARHWAL
BALLIA
PAPUM PARE
LAKHIMPUR
RAISEN
BHANDARA
SHIVPURI
HINGOLI
KANGRA
MANDI
SOLAN
DIBANG VALLEY
WARDHA
WEST GODAVARI
HASSAN
KANGRA
PITHORAGARH
TEHRI GARHWAL
BULANDSHAHR
DEORIA
MAU
MAU
EAST SINGHBUM
PURI
CHANDRAPUR
WARDHA
WARDHA
YAVATMAL
DAVANGERE
UTTARA KANNADA
SHIMLA
PAURI GARHWAL
AMBALA
HANUMANGARH
AZAMGARH
GHAZIPUR
CACHAR
EAST SINGHBUM
BOUDH
RAJNANDGAON
HINGOLI
SOLAN
HOSHIARPUR
ALMORA
PAURI GARHWAL
PAURI GARHWAL
ALWAR
ALWAR
PRAYAGRAJ
BARABANKI
PILIBHIT
TINSUKIA
NAGPUR
DHARWAD
SHIVAMOGGA
LAHUL AND SPITI
MANDI
SOLAN
PAURI GARHWAL
PITHORAGARH
GANGANAGAR
BASTI
BUDAUN
JUNAGADH
PITHORAGARH
SHIMLA
ALMORA
CHAMOLI
GANGANAGAR
KARIMGANJ
NADIA
DUMKA
ANUGUL
REWA
SHIMLA
SHIMLA
PAURI GARHWAL
GANGANAGAR
KOTA
BALLIA
BANDA
BHADOHI
AURANGABAD
GODDA
SATNA
SEHORE
KATHUA
BAGESHWAR
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
JAISALMER
JHANSI
GAYA
KANDHAMAL
KENDRAPARA
NAYAGARH
BETUL
HAMIRPUR
KANGRA
ALMORA
PAURI GARHWAL
PAURI GARHWAL
BUNDI
KOTA
CHITRAKOOT
GORAKHPUR
BALESHWAR
NAYAGARH
NARSINGHPUR
HASSAN
SHIMLA
SHIMLA
SHIMLA
BUNDI
BALLIA
SARAN
DIMA HASAO
Jhargram
SAHEBGANJ
ANUGUL
BALESHWAR
BENGALURU URBAN
MANDI
PAURI GARHWAL
PITHORAGARH
SIVASAGAR
Jhargram
GANJAM
KANDHAMAL
CHAMBA
MANDI
CHAMPAWAT
PAURI GARHWAL
RUDRA PRAYAG
NADIA
PALAMU
BHIND
SATNA
GIR SOMNATH
KANGRA
SOLAN
PAURI GARHWAL
PITHORAGARH
SAWAI MADHOPUR
BAREILLY
NORTH GARO HILLS
MEDINIPUR EAST
HAZARIBAGH
MAYURBHANJ
SAMBALPUR
KOLAR
TUMAKURU
BAGESHWAR
PAURI GARHWAL
HANUMANGARH
NAYAGARH
PURI
HASSAN
ALMORA
ALMORA
CHAMOLI
MATHURA
DIBRUGARH
PAKUR
JAGATSINGHAPUR
GONDIA
HAMIRPUR
KANGRA
SHIMLA
JALANDHAR
KARAULI
BALLIA
JAUNPUR
PILIBHIT
VARANASI
EAST KHASI HILLS
MEDINIPUR WEST
NANDED
KANGRA
SHIMLA
PAURI GARHWAL
PAURI GARHWAL
GHAZIPUR
GORAKHPUR
MAU
PILIBHIT
KARBI ANGLONG
DEOGHAR
BALAGHAT
ALMORA
HASSAN
MANDI
SOLAN
BIJNOR
CHANDAULI
GHAZIPUR
RAMPUR
LAKHIMPUR
PURBA BARDHAMAN
GANJAM
DAMOH
BENGALURU RURAL
SOUTH GOA
SOLAN
BAGESHWAR
CHAMPAWAT
AZAMGARH
MEDINIPUR WEST
PALAMU
RAYAGADA
SONEPUR
BALRAMPUR
UTTAR KASHI
SHIMLA
HARIDWAR
BAREILLY
BIJNOR
BHAGALPUR
BANKURA
Jhargram
RAMGARH
GANJAM
SEONI
BHANDARA
CHIKKABALLAPURA
PAURI GARHWAL
GANGANAGAR
GHAZIPUR
KUSHI NAGAR
DIBRUGARH
ANUGUL
BOUDH
GADAG
RUPNAGAR
BAGESHWAR
BAGESHWAR
PITHORAGARH
HANUMANGARH
BASTI
DEORIA
KHERI
MEERUT
DARBHANGA
LOWER SUBANSIRI
LOWER SUBANSIRI
JORHAT
GODDA
MAYURBHANJ
KHARGONE
SHIMLA
SHIMLA
UNA
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
AGRA
SARAIKELA KHARSAWAN
ALMORA
KALAHANDI
BALAGHAT
REWA
SIDHI
NAGPUR
PARBHANI
CHAMOLI
PAURI GARHWAL
PAURI GARHWAL
TEHRI GARHWAL
TONK
BIJNOR
JALAUN
JAGATSINGHAPUR
PILIBHIT
SOUTH GARO HILLS
MEDINIPUR WEST
DEOGHAR
DHAR
CHANDRAPUR
HASSAN
MYSURU
SHIVAMOGGA
HAMIRPUR
MANDI
MANDI
MANDI
SOLAN
PAURI GARHWAL
PAURI GARHWAL
BHARATPUR
BIJNOR
MIRZAPUR
SAHARANPUR
HAPUR
MEDINIPUR EAST
HAZARIBAGH
BALESHWAR
UTTARA KANNADA
CHAMBA
PAURI GARHWAL
RUDRA PRAYAG
AZAMGARH
GHAZIPUR
LALITPUR
MIRZAPUR
PALAMU
ANUGUL
BALAGHAT
NEEMUCH
SHEOPUR
AMRAVATI
HASSAN
CHIKKABALLAPURA
SOLAN
PITHORAGARH
PITHORAGARH
FATEHPUR
BASTI
GARHWA
TUMAKURU
JAMMU
SAMBA
BILASPUR
UTTAR KASHI
SANT KABEER NAGAR
KAIMUR (BHABUA)
HASSAN
HOSHIARPUR
ALMORA
CHAMOLI
TEHRI GARHWAL
TAWANG
DHEMAJI
CHHINDWARA
KHARGONE
REWA
CHIKKABALLAPURA
VIRUDHUNAGAR
SHIMLA
ALMORA
BHILWARA
GORAKHPUR
MIRZAPUR
MEDINIPUR WEST
SATNA
PAURI GARHWAL
HASSAN
UTTARA KANNADA
KANGRA
SHIMLA
CHAMPAWAT
YAMUNANAGAR
MUZAFFARPUR
LOHIT
LOWER SUBANSIRI
DHENKANAL
SINGRAULI
NAGPUR
CHIKKAMAGALURU
LAHUL AND SPITI
MANDI
MANDI
SHIMLA
SOLAN
ALMORA
TEHRI GARHWAL
PRATAPGARH
BALESHWAR
MUNGELI
CHHINDWARA
UTTARA KANNADA
SHIMLA
SOLAN
PAURI GARHWAL
JAIPUR
LOWER SUBANSIRI
KAMRUP METRO
ANUGUL
AMRAVATI
NAGPUR
NAGPUR
YAVATMAL
CHAMBA
KANGRA
LAHUL AND SPITI
BAGESHWAR
PAURI GARHWAL
PAURI GARHWAL
KANPUR NAGAR
MEERUT
SHEOPUR
SOUTH ANDAMANS
TEHRI GARHWAL
GHAZIPUR
LALITPUR
SAMASTIPUR
KOKRAJHAR
KANDHAMAL
PITHORAGARH
BIJNOR
KANDHAMAL
NAYAGARH
AKOLA
MANDI
SHIMLA
PAURI GARHWAL
BIJNOR
KANGPOKPI
UMARIA
KOLAR
KINNAUR
SHIMLA
CHAMPAWAT
PAURI GARHWAL
SIRSA
KOTA
JALAUN
AMROHA
MEDINIPUR WEST
DEOGHAR
KANDHAMAL
KENDRAPARA
RAISEN
PUNE
MANDI
SAMBA
HAMIRPUR
KINNAUR
CHAMOLI
PAURI GARHWAL
UTTAR KASHI
BHARATPUR
BASTI
PILIBHIT
SHAHJAHANPUR
NADIA
BALESHWAR
SAMBALPUR
SOLAN
CHAMOLI
PAURI GARHWAL
JAUNPUR
RAMPUR
SONBHADRA
BALESHWAR
MAYURBHANJ
NAYAGARH
PURI
BHANDARA
YAVATMAL
TUMAKURU
KINNAUR
PATIALA
PAURI GARHWAL
TEHRI GARHWAL
TEHRI GARHWAL
GHAZIPUR
PALAMU
BOUDH
UMARIA
MANDI
PAURI GARHWAL
PITHORAGARH
PRAYAGRAJ
AZAMGARH
BASTI
SANT KABEER NAGAR
SIDDHARTH NAGAR
NAGAON
GODDA
KANDHAMAL
SAGAR
KOLAR
HAMIRPUR
KAIMUR (BHABUA)
MANDSAUR
SHAJAPUR
WARDHA
UTTARA KANNADA
MANDI
CHAMPAWAT
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
BASTI
BANKURA
BALAGHAT
REWA
BULDHANA
LAKSHADWEEP DISTRICT
SOLAN
GURDASPUR
BAGESHWAR
BAGESHWAR
CHAMPAWAT
TEHRI GARHWAL
SULTANPUR
GOPALGANJ
WEST KARBI ANGLONG
MEDINIPUR WEST
EAST SINGHBUM
KODERMA
SAHEBGANJ
GARIYABAND
HOSHANGABAD
WARDHA
SHIVAMOGGA
RANGA REDDY
SOLAN
CHAMOLI
PAURI GARHWAL
BHARATPUR
HANUMANGARH
LOWER SUBANSIRI
SOUTH GARO HILLS
JORHAT
DINAJPUR DAKSHIN
ANUGUL
NAYAGARH
NAYAGARH
RAISEN
REWA
NAGPUR
WARDHA
RAMANAGARA
SIDDIPET
BAREILLY
CHANDAULI
SARAIKELA KHARSAWAN
JAJAPUR
ASHOKNAGAR
REWA
AKOLA
NICOBARS
SHIMLA
CHAMOLI
MIRZAPUR
TIRAP
ANUGUL
REWA
SHIMLA
SHIMLA
SHIMLA
SHIMLA
PAURI GARHWAL
PITHORAGARH
CHITTORGARH
GONDA
MIRZAPUR
DIBANG VALLEY
KARIMGANJ
MEDINIPUR WEST
BHADRAK
UTTARA KANNADA
SHIMLA
HOSHIARPUR
NAINITAL
PITHORAGARH
CHURU
BASTI
SOUTH GARO HILLS
CUTTACK
GADAG
HASSAN
HAMIRPUR
MANDI
SHIMLA
LOWER SUBANSIRI
KANGRA
KANGRA
SHIMLA
SOLAN
PAURI GARHWAL
PAURI GARHWAL
CHANDAULI
GOLAGHAT
BANKURA
KHORDHA
PAURI GARHWAL
NAGPUR
NICOBARS
SAMBA
SHIMLA
SOLAN
SOLAN
CHAMOLI
PITHORAGARH
BALLIA
BIJNOR
WEST DISTRICT
LOWER SUBANSIRI
SIVASAGAR
HAZARIBAGH
LATEHAR
BALESHWAR
JABALPUR
YAVATMAL
DAVANGERE
BAGESHWAR
PAURI GARHWAL
AZAMGARH
GORAKHPUR
EAST KHASI HILLS
PURULIA
ANUGUL
SHEOPUR
SINGRAULI
KANGRA
SOLAN
ALMORA
PAURI GARHWAL
CHURU
DEORIA
MORADABAD
HOOGHLY
PURULIA
JAMTARA
KALAHANDI
AURANGABAD
MANDI
BAGESHWAR
BAGESHWAR
PAURI GARHWAL
CACHAR
DHENKANAL
AKOLA
WARDHA
CHIKKABALLAPURA
MANDI
MANDI
BAGESHWAR
NAINITAL
BHILWARA
SAHARANPUR
LAKHIMPUR
MEDINIPUR WEST
SAMBALPUR
CHAMOLI
HARIDWAR
PAURI GARHWAL
BALESHWAR
EAST KHASI HILLS
ALMORA
DIMA HASAO
BALESHWAR
KANDHAMAL
HANUMANGARH
YAVATMAL
Jhargram
MYSURU
NAINITAL
PAURI GARHWAL
AJMER
AZAMGARH
HANUMANGARH
JAUNPUR
MIRZAPUR
VARANASI
GAYA
BIRBHUM
DUMKA
BALESHWAR
REWA
AMRAVATI
DEOGHAR
HASSAN
HAMIRPUR
KANGRA
KANGRA
KINNAUR
MANDI
LUDHIANA
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
TEHRI GARHWAL
SONIPAT
JAIPUR
SHAHJAHANPUR
NAGAON
BOUDH
DHENKANAL
DEWAS
BHANDARA
MYSURU
UTTARA KANNADA
NORTH AND MIDDLE ANDAMAN
SOLAN
BAGESHWAR
NAINITAL
PAURI GARHWAL
BUNDI
CHANDAULI
DEORIA
SAHARANPUR
SONBHADRA
VARANASI
PURBI CHAMPARAN
KENDRAPARA
SHIMLA
SHIMLA
PAURI GARHWAL
TEHRI GARHWAL
BIJNOR
SULTANPUR
MEDINIPUR WEST
Jhargram
CHATRA
DHANBAD
DHENKANAL
NAYAGARH
SIDHI
AKOLA
OSMANABAD
MANDI
UNA
BAGESHWAR
PAURI GARHWAL
PAURI GARHWAL
PAURI GARHWAL
CHANDAULI
EAST DISTRICT
MEDINIPUR WEST
MEDINIPUR WEST
MAYURBHANJ
WARDHA
VIZIANAGARAM
CHAMARAJANAGARA
TUMAKURU
PAURI GARHWAL
PAURI GARHWAL
MAHARAJGANJ
ANUGUL
RAIGAD
HASSAN
MANDI
SIRMAUR
TEHRI GARHWAL
KARNAL
MEERUT
SONEPUR
BALAGHAT
MANDI
SHIMLA
SOLAN
CHAMOLI
PAURI GARHWAL
PAURI GARHWAL
JAUNPUR
JAUNPUR
SANT KABEER NAGAR
PALAMU
BALOD
BULDHANA
CHAMOLI
HOSHIARPUR
Tarn Taran
TEHRI GARHWAL
ALWAR
AZAMGARH
GORAKHPUR
KAMRUP
MEDINIPUR WEST
NAYAGARH
PURI
JABALPUR
RAJGARH
KANGRA
MANDI
MANDI
MANDI
CHAMOLI
NAINITAL
PAURI GARHWAL
AMROHA
MATHURA
DUMKA
JAGATSINGHAPUR
CHHINDWARA
CHHINDWARA
BENGALURU RURAL
BILASPUR
CHAMBA
MANDI
ALMORA
CHAMOLI
GHAZIPUR
BHAGALPUR
JORHAT
LAKHIMPUR
BALESHWAR
SHIVPURI
AMRAVATI
ANANTAPUR
CHIKKABALLAPURA
CHAMBA
KANGRA
MANDI
ALMORA
PAURI GARHWAL
TEHRI GARHWAL
UTTAR KASHI
UTTAR KASHI
REWARI
DIBRUGARH
GOLAGHAT
MARIGAON
NAYAGARH
JAMMU
RAISEN
WARDHA
HASSAN
KOLAR
TIRUVANNAMALAI
BIJNOR
KAIMUR (BHABUA)
DUMKA
SAMBALPUR
KATNI
AMRAVATI
SOLAN
PAURI GARHWAL
UTTAR KASHI
GANGANAGAR
PILIBHIT
EAST SINGHBUM
ANUGUL
SATNA
AMRAVATI
PARBHANI
HASSAN
UTTARA KANNADA
MANDI
UNA
BAGESHWAR
PAURI GARHWAL
RUDRA PRAYAG
BASTI
KALAHANDI
REWA
SOLAN
ALMORA
PAURI GARHWAL
AZAMGARH
BASTI
BIJNOR
ANUGUL
NARSINGHPUR
SATNA
RAIGAD
KANGRA
BAGESHWAR
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
TEHRI GARHWAL
PRAYAGRAJ
HARDOI
MIRZAPUR
BIRBHUM
DEOGHAR
NAYAGARH
KATNI
AMRAVATI
NAGPUR
HASSAN
KANGRA
SHIMLA
ALMORA
TEHRI GARHWAL
BALESHWAR
MAYURBHANJ
REWA
TUMAKURU
SHIMLA
PATHANKOT
PAURI GARHWAL
TEHRI GARHWAL
UTTAR KASHI
PRATAPGARH
PRAYAGRAJ
SONITPUR
CUTTACK
DHENKANAL
WARDHA
SHIMLA
SHIMLA
UNA
BHARATPUR
BIKANER
GANGANAGAR
UDAIPUR
BAREILLY
BUDAUN
CHANDAULI
JALAUN
HAPUR
LOWER SUBANSIRI
BALESHWAR
WARDHA
RUDRA PRAYAG
RUDRA PRAYAG
UTTAR KASHI
AZAMGARH
FARRUKHABAD
HAMIRPUR
MAU
SANT KABEER NAGAR
PURNIA
GWALIOR
BULDHANA
CHIKKAMAGALURU
HAMIRPUR
LAHUL AND SPITI
SHIMLA
JAIPUR
MIRZAPUR
SAHARSA
VAISHALI
Biswanath
BALESHWAR
NAYAGARH
CHITRADURGA
KOLAR
ALMORA
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
TEHRI GARHWAL
NAWADA
MEDINIPUR EAST
MEDINIPUR WEST
MEDINIPUR WEST
DEOGHAR
GANJAM
SHIVAMOGGA
CHIKKABALLAPURA
RAMANAGARA
JAMMU
GURDASPUR
ALMORA
BHARATPUR
SAHARANPUR
ROHTAS
BARPETA
DHEMAJI
MAJULI
ANUGUL
WARDHA
CHIKKAMAGALURU
JAMMU
UNA
PAURI GARHWAL
SAWAI MADHOPUR
GHAZIPUR
JALAUN
MUZAFFARNAGAR
SULTANPUR
RAJNANDGAON
BENGALURU RURAL
TIRUVANNAMALAI
CHENGALPATTU
SOLAN
CHAMPAWAT
HAPUR
GIRIDIH
ANUGUL
BETUL
AMRAVATI
SINDHUDURG
CHAMBA
MANDI
CHAMOLI
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
BASTI
JAUNPUR
MAU
AURANGABAD
MEDINIPUR WEST
WARDHA
UTTARA KANNADA
CHAMBA
CHAMOLI
PAURI GARHWAL
PITHORAGARH
RUDRA PRAYAG
PRAYAGRAJ
DHEMAJI
DIBRUGARH
GODDA
GAJAPATI
MAYURBHANJ
NAYAGARH
JANJGIR-CHAMPA
BETUL
DATIA
KOLAR
TUMAKURU
TUMAKURU
HAMIRPUR
SOLAN
UNA
HOSHIARPUR
PAURI GARHWAL
PAURI GARHWAL
KURUKSHETRA
GHAZIPUR
EAST SINGHBUM
MAYURBHANJ
BIJAPUR
REWA
SHIMLA
KAPURTHALA
BAGESHWAR
CHAMOLI
PAURI GARHWAL
NUH
GORAKHPUR
PILIBHIT
RAISEN
SAGAR
TUMAKURU
MANDI
SHIMLA
AZAMGARH
SHRAVASTI
Biswanath
BIRBHUM
Jhargram
RAYAGADA
BETUL
KANGRA
KANGRA
LAHUL AND SPITI
SOLAN
PAURI GARHWAL
BASTI
CHANDAULI
CHANGLANG
WEST KAMENG
SONEPUR
WARDHA
YADGIR
DEHRADUN
HANUMANGARH
BANKURA
MALDAH
MEDINIPUR WEST
KODERMA
CHAMARAJANAGARA
SATNA
LAHUL AND SPITI
KINNAUR
MANDI
ALMORA
BAGESHWAR
BAGESHWAR
TEHRI GARHWAL
HANUMANGARH
BIJNOR
GAUTAM BUDDHA NAGAR
GHAZIPUR
GHAZIPUR
BANKURA
VIDISHA
SHIMLA
HAMIRPUR
MANDI
MANDI
MANDI
MANDI
SOLAN
PAURI GARHWAL
PAURI GARHWAL
MAU
MIRZAPUR
WEST DISTRICT
WEST JAINTIA HILLS
ANUGUL
KHORDHA
SOLAN
PITHORAGARH
DHEMAJI
DEOGARH
GAJAPATI
NAYAGARH
CHANDRAPUR
PAURI GARHWAL
MANDI
SOLAN
ALMORA
ALMORA
ALMORA
CHAMOLI
AYODHYA
GHAZIPUR
RAE BARELI
BHADOHI
DHANBAD
PATNA
BIRBHUM
BETUL
SATNA
BENGALURU RURAL
CHIKKAMAGALURU
CHITRADURGA
KINNAUR
KINNAUR
CHAMOLI
PAURI GARHWAL
RAE BARELI
KODERMA
CHATRA
JHARSUGUDA
KORAPUT
AKOLA
AKOLA
NICOBARS
SOLAN
SOLAN
CHAMOLI
GORAKHPUR
JHANSI
DUMKA
GODDA
NAYAGARH
KANDHAMAL
MAYURBHANJ
AKOLA
BENGALURU URBAN
MANDI
SHIMLA
NAINITAL

In [48]:
dist_highest_literacy_female = census[census['Female-LR'] == highest_lrfemale].index.tolist()
print("District with the highest female literacy rate:")
for dist in dist_highest_literacy_female:
    print(census.loc[dist,'District'])

District with the highest female literacy rate:
BARAMULLA
MANDI
BASTI
UNNAO
GOPALGANJ
KAMRUP
DHANBAD
ANUGUL
REWA
MYSURU
RAMANAGARA
BILASPUR
SOLAN
Tarn Taran
PAURI GARHWAL
WEST KAMENG
DEOGHAR
AMRAVATI
NAGPUR
RATNAGIRI
KOLAR
UTTARA KANNADA
KULLU
SHIMLA
GANGANAGAR
COOCHBEHAR
Jhargram
GANJAM
CHIKKAMAGALURU
SOLAN
BANKA
KOLAR
KINNAUR
BALLIA
JAJAPUR
KOREA
RUDRA PRAYAG
SAHARANPUR
MEDINIPUR WEST
WARDHA
UTTARA KANNADA
SOLAN
PAURI GARHWAL
WARDHA
CHENGALPATTU
NAYAGARH
VIZIANAGARAM
HARIDWAR
SRIKAKULAM
TUMAKURU
MAHOBA
JALANDHAR
BALLIA
HAPUR
JAJAPUR
LAHUL AND SPITI
SHIMLA
MEDINIPUR WEST
BALESHWAR
JAGATSINGHAPUR
SAGAR
BANKURA
MEDINIPUR WEST
ANUGUL
SHIVAMOGGA
SOLAN
AYODHYA
KHORDHA
EAST GODAVARI
AKOLA
MANDI
REWA
YAVATMAL
TEHRI GARHWAL
SAHARANPUR
MURSHIDABAD
DUMKA
SHIVAMOGGA
HAMIRPUR
MANDI
PAURI GARHWAL
LAHUL AND SPITI
SHIMLA
SOLAN
RUDRA PRAYAG
DUMKA
BALAGHAT
RAISEN
RATNAGIRI
SHIVAMOGGA
KRISHNAGIRI
CHAMPAWAT
HANUMANGARH
Jhargram
TINSUKIA
BIRBHUM
GIRIDIH
AMRAVATI
FEROZEPUR
CHAMOLI
PURI
PURI
UTTARA KANNADA
CHAMBA
PITHORAGARH
KARNAL
KARBI ANGLONG
JAJAPUR
CHITRADURGA
KHERI
PAURI GARHWAL
BAGESHWAR
CUTTACK
KANDHAMAL
KINNAUR
BAGESHWAR
DINAJPUR DAKSHIN
SATNA
KOPPAL
MANDI
MANDI
PAURI GARHWAL
EAST KHASI HILLS
INDORE
BENGALURU RURAL
PAURI GARHWAL
SATNA
PAURI GARHWAL
MANDI
Jhargram
BASTI
SARAIKELA KHARSAWAN
RAISEN
RATNAGIRI
CHIKKAMAGALURU
LAHUL AND SPITI
DEOGHAR
CHAMPAWAT
KOTA
BENGALURU RURAL
NAGAUR
PILIBHIT
BANKA
ANUGUL
PANNA
LOWER SUBANSIRI
EAST SINGHBUM
DAUSA
JAUNPUR
RAISEN
RAISEN
SIDHI
RAMANAGARA
GURDASPUR
JORHAT
PALAMU
BAREILLY
YADGIR
SOUTH ANDAMANS
BAGESHWAR
MEDINIPUR WEST
KHUNTI
CHITRADURGA
SHIVAMOGGA
JALAUN
MIRZAPUR
LATEHAR
CHHINDWARA
HASSAN
KOLAR
TUMAKURU
KANGRA
SOLAN
GHAZIPUR
GHAZIPUR
COOCHBEHAR
TUMAKURU
MANDI
PAURI GARHWAL
BALLIA
BASTI
VAISHALI
LOWER SUBANSIRI
ANUGUL
SINDHUDURG
SANT KABEER NAGAR
CHURACHANDPUR
West Tripura
CUTTACK
YADGIR
HANUMANGARH
NARSINGHPUR
RATLAM
BANKA
LOWER SUBANSIRI
NAGAON
SATNA
CHANDRAPUR
KOLAR
SHIMLA
JALAUN
MADHEPURA
Jhargram
WARDHA
RAE BARELI
SITAMARHI
LOWER SUBANSIRI
LATEHAR
NAGPUR
DAVANGERE
TUMAKURU
MANDI
PAURI GARHWAL
GORAKHPUR
BENGALURU RURAL
SOLAN
GURDASPUR
BALESHWAR
RATLAM
WARDHA
ALMORA
CHAMOLI
CHAMOLI
ALIGARH
GONDA
VARANASI
BANKA
MANDI
SHIMLA
PAURI GARHWAL
PALAMU
KODAGU
KUPWARA
HAMIRPUR
PAURI GARHWAL
BASTI
GORAKHPUR
CHIKKABALLAPURA
MIRZAPUR
JAJAPUR
NAYAGARH
SUNDARGARH
SRIKAKULAM
KANGRA
PAURI GARHWAL
MEDINIPUR EAST
KACHCHH
WASHIM
MYSURU
UTTARA KANNADA
AZAMGARH
MEDINIPUR EAST
EAST GARO HILLS
LAKHIMPUR
CHIKKAMAGALURU
CHAMBA
KANGRA
MANDI
SHIMLA
SHIMLA
RAMPUR
REWA
SHAHDOL
DEOGHAR
JAMTARA
KENDRAPARA
PITHORAGARH
GHAZIPUR
PALAMU
NAMAKKAL
AZAMGARH
SHAHJAHANPUR
DHEMAJI
DUMKA
KOLAR
PAURI GARHWAL
VISAKHAPATANAM
YAMUNANAGAR
CUTTACK
MAYURBHANJ
MANDI
PAURI GARHWAL
SONBHADRA
DINAJPUR DAKSHIN
ANUGUL
LAHUL AND SPITI
DIBRUGARH
KAMRUP
KODERMA
BILASPUR
KHUNTI
KALLAKURICHI
LOWER SUBANSIRI
CHAMBA
KINNAUR
NORTH DISTRICT
AZAMGARH
TUMAKURU
BIKANER
SITAMARHI
MAYURBHANJ
RAJNANDGAON
BALAGHAT
LAKSHADWEEP DISTRICT
CHENGALPATTU
HAMIRPUR
BHANDARA
KAPURTHALA
SULTANPUR
ROHTAS
MEDINIPUR WEST
GIRIDIH
WASHIM
JAMMU
KANGRA
GHAZIPUR
GODDA
PITHORAGARH
KAIMUR (BHABUA)
PAURI GARHWAL
LOWER SUBANSIRI
WEST JAINTIA HILLS
DIMA HASAO
THANJAVUR
CHURACHANDPUR
REWA
CHAMOLI
MIRZAPUR
KHORDHA
RAMPUR
TAWANG
SHIMLA
DIBANG VALLEY
PAPUM PARE
KENDRAPARA
SOLAN
AZAMGARH
VIDISHA
WEST GODAVARI
MAU
CHANDRAPUR
PITHORAGARH
GHAZIPUR
CACHAR
KALAHANDI
HOSHIARPUR
PAURI GARHWAL
MEERUT
CHIKKAMAGALURU
REWA
SHIMLA
CHAMOLI
SAMBHAL
KARIMGANJ
BALESHWAR
PAURI GARHWAL
GANGANAGAR
MAYURBHANJ
SEHORE
AURAIYA
JHANSI
Biswanath
NAINITAL
PAURI GARHWAL
BALESHWAR
HASSAN
SHIMLA
HOOGHLY
Jhargram
BALESHWAR
MANDI
GANJAM
ALMORA
NADIA
SATNA
LAHUL AND SPITI
SOLAN
ALMORA
NORTH GARO HILLS
GIRIDIH
KHORDHA
BENGALURU RURAL
LAHUL AND SPITI
PATHANKOT
MEDINIPUR WEST
PAKUR
KANGRA
SHIMLA
SOLAN
JALANDHAR
MEDINIPUR WEST
PILIBHIT
MANDI
BIJNOR
GHAZIPUR
RAMPUR
KATIHAR
CHAMPAWAT
EAST KHASI HILLS
BALRAMPUR
DAVANGERE
MAU
LAKHIMPUR
KALIMPONG
Jhargram
CHIKKAMAGALURU
HASSAN
HASSAN
CHIKKABALLAPURA
GHAZIPUR
TUENSANG
GADAG
BAGESHWAR
JAUNPUR
KHERI
DARBHANGA
DIBANG VALLEY
LOWER SUBANSIRI
JORHAT
KHORDHA
SAMBALPUR
SAMBALPUR
MAU
REWA
LALITPUR
PILIBHIT
SHIVAMOGGA
MANDI
BHARATPUR
MIRZAPUR
SAHARANPUR
BALESHWAR
PAURI GARHWAL
BALAGHAT
HASSAN
HAMIRPUR
FATEHPUR
SOUTH GARO HILLS
LAKHIMPUR
UTTARA KANNADA
KAIMUR (BHABUA)
HASSAN
MEDINIPUR WEST
GAJAPATI
CHHINDWARA
WARDHA
VIRUDHUNAGAR
GORAKHPUR
MEDINIPUR WEST
SATNA
MANDI
CHIKKAMAGALURU
MANDI
ALMORA
NARSINGHPUR
HASSAN
AMRAVATI
SHIMLA
MEERUT
SONBHADRA
BHAGALPUR
PAURI GARHWAL
KOKRAJHAR
BHANDARA
GURDASPUR
BIJNOR
AKOLA
NORTH AND MIDDLE ANDAMAN
LAHUL AND SPITI
JALANDHAR
BIJNOR
KARBI ANGLONG
SIRSA
MAU
RAJNANDGAON
RAISEN
MANDI
HAMIRPUR
UTTAR KASHI
SHAHJAHANPUR
LOWER SUBANSIRI
BANKURA
WARDHA
CHENGALPATTU
SHIMLA
MAHARAJGANJ
RAMPUR
BALESHWAR
MAYURBHANJ
CHENGALPATTU
HASSAN
KAPURTHALA
SONBHADRA
GAYA
KAIMUR (BHABUA)
SIROHI
BASTI
MEDINIPUR EAST
GURDASPUR
BAGESHWAR
PAURI GARHWAL
TEHRI GARHWAL
DIBANG VALLEY
MEDINIPUR WEST
SAHEBGANJ
PURI
GARIYABAND
UTTARA KANNADA
SOLAN
JORHAT
DINAJPUR DAKSHIN
WEST SINGHBHUM
REWA
NAGPUR
CHIKKAMAGALURU
MANDI
TEHRI GARHWAL
FATEHPUR
GORAKHPUR
HAMIRPUR
SHIMLA
GURDASPUR
CHAMPAWAT
DHEMAJI
ANUGUL
KORAPUT
REWA
SHIMLA
SHIMLA
MIRZAPUR
GODDA
UTTARA KANNADA
SHIMLA
NAINITAL
KATHUA
LOWER SUBANSIRI
SATNA
KANGRA
SOLAN
UNA
GOLAGHAT
BANKURA
SOLAN
EAST KHASI HILLS
BALESHWAR
DAVANGERE
ANUGUL
REWA
SINGRAULI
AMRAVATI
ALMORA
MORADABAD
AURANGABAD
REASI
MANDI
CACHAR
NAYAGARH
GONDIA
NAGPUR
WARDHA
MANDI
SHIMLA
GHAZIPUR
CHATRA
DUMKA
SAMBALPUR
MEDINIPUR WEST
ALMORA
MYSURU
LAHUL AND SPITI
JAUNPUR
PAKKE KESSANG
BIRBHUM
AZAMGARH
UTTARA KANNADA
SOLAN
PURBI CHAMPARAN
Jhargram
LOWER DIBANG VALLEY
Jhargram
CHATRA
DHENKANAL
OSMANABAD
RATNAGIRI
WARDHA
PAURI GARHWAL
CHANDAULI
CHAMARAJANAGARA
TUMAKURU
CHAMPAWAT
PITHORAGARH
CHANGLANG
WEST KAMENG
CHIKKAMAGALURU
MANDI
SONEPUR
JAUNPUR
HOSHIARPUR
NAINITAL
KAMRUP
MEDINIPUR WEST
NAYAGARH
JABALPUR
RAJGARH
MANDI
GORAKHPUR
MATHURA
BENGALURU RURAL
BILASPUR
BHAGALPUR
JORHAT
PAURI GARHWAL
LOWER SUBANSIRI
GOLAGHAT
MARIGAON
WARDHA
KOLAR
TUMAKURU
KANGRA
KINNAUR
PAURI GARHWAL
SOUTH WEST KHASI HILLS
SOLAN
PARBHANI
UNA
RUPNAGAR
PAURI GARHWAL
NARSINGHPUR
HARIDWAR
AZAMGARH
BASTI
ANUGUL
KHORDHA
KHORDHA
NARSINGHPUR
SATNA
RAIGAD
KANGRA
MIRZAPUR
BALESHWAR
RAIGAD
THANJAVUR
SHIMLA
REWA
SOLAN
SOLAN
PATHANKOT
PRATAPGARH
CUTTACK
SAGAR
SHIMLA
UNA
CHANDAULI
NICOBARS
AZAMGARH
BULDHANA
CHIKKAMAGALURU
HASSAN
KALLAKURICHI
PRATAPGARH
AZAMGARH
SAHARSA
MEDINIPUR WEST
BALESHWAR
GAJAPATI
SATNA
KOLAR
PAURI GARHWAL
PITHORAGARH
PITHORAGARH
GHAZIPUR
MEDINIPUR EAST
ANUGUL
SIDHI
JAMMU
MANDI
SHIMLA
GURDASPUR
HOSHIARPUR
BARPETA
DHEMAJI
DHEMAJI
CHIKKAMAGALURU
ALMORA
MUZAFFARNAGAR
Jhargram
KORAPUT
RAJNANDGAON
CHENGALPATTU
SOLAN
BETUL
SHIMLA
PAURI GARHWAL
MAU
SHIMLA
PAURI GARHWAL
PITHORAGARH
GANGANAGAR
GANGANAGAR
DHEMAJI
DIBRUGARH
NAYAGARH
JANJGIR-CHAMPA
HOSHIARPUR
PURULIA
SOLAN
BAGESHWAR
PILIBHIT
RAISEN
SHEOPUR
TUMAKURU
FIROZABAD
MAHOBA
Biswanath
BHAVNAGAR
HAMIRPUR
NAINITAL
CHANDAULI
NAYAGARH
PURI
SONEPUR
BETUL
SATARA
BIJNOR
MALDAH
BAGESHWAR
PITHORAGARH
GHAZIPUR
KODERMA
VIDISHA
SHIMLA
MANDI
HANUMANGARH
ANUGUL
WEST GODAVARI
CHAMBA
SOLAN
KRISHNAGIRI
AYODHYA
GHAZIPUR
BETUL
CHIKKAMAGALURU
CHITRADURGA
CHAMOLI
SHAHJAHANPUR
KODERMA
SOLAN
AKOLA
AKOLA
JHANSI
MAYURBHANJ
HANUMANGARH
SONITPUR
MEDINIPUR WEST
BALESHWAR
NAGPUR
PAURI GARHWAL
GANJAM
KHORDHA
LOHIT
CHITRADURGA
SOUTH GOA
HANUMANGARH
KARBI ANGLONG
MEDINIPUR WEST
GANJAM
MAYURBHANJ
SHIMLA
SOLAN
SHAHJAHANPUR
BHANDARA
SHIVAMOGGA
SOUTH DISTRICT
DINAJPUR DAKSHIN
BASTI
CHURU
GANGANAGAR
MIRZAPUR
SUNDARGARH
REWA
CUTTACK
SHIMLA
BARAN
BAHRAICH
SOUTH WEST KHASI HILLS
MEDINIPUR EAST
NARSINGHPUR
HAMIRPUR
GORAKHPUR
DIBANG VALLEY
SAMBALPUR
SHAHJAHANPUR
SIDDHARTH NAGAR
LOWER SUBANSIRI
MEDINIPUR WEST
Jhargram
CHIKKAMAGALURU
HASSAN
SHIVAMOGGA
BASTI
KANGRA
SOLAN
NAINITAL
KOLAR
ALMORA
AMBEDKAR NAGAR
BHADOHI
REWA
TUMAKURU
KANGRA
SOLAN
TUTICORIN
LAHUL AND SPITI
BHADRAK
BIJAPUR
CHAMARAJANAGARA
SHIMLA
CHAMPAWAT
JAIPUR
Biswanath
KATNI
LAHUL AND SPITI
HOSHIARPUR
ALMORA
MEERUT
CHIRANG
DHENKANAL
SIDHI
HASSAN
BARNALA
SAWAI MADHOPUR
DHEMAJI
KARBI ANGLONG
SHIVPURI
SRIKAKULAM
KANNIYAKUMARI
CHAMPAWAT
SAHEBGANJ
GANJAM
SHAJAPUR
WARDHA
GHAZIPUR
SATNA
SOLAN
ALMORA
GANGANAGAR
NEEMUCH
ROHTAS
LAKHIMPUR
SHIVAMOGGA
DIBRUGARH
DEOGHAR
MAYURBHANJ
WASHIM
VIZIANAGARAM
PAURI GARHWAL
JAUNPUR
MAU
GODDA
NAYAGARH
CHANDRAPUR
RATNAGIRI
DEHRADUN
PANCHKULA
HANUMANGARH
AYODHYA
GHAZIPUR
KOLAR
TUMAKURU
KANGRA
PITHORAGARH
BASTI
WEST KAMENG
Jhargram
NAGPUR
PAURI GARHWAL
SOUTH GARO HILLS
PURULIA
DEOGHAR
BALESHWAR
GIR SOMNATH
KOPPAL
KANGRA
LAHUL AND SPITI
SHIMLA
PAURI GARHWAL
PITHORAGARH
MUZAFFARPUR
EAST SINGHBUM
DIBANG VALLEY
LAHUL AND SPITI
Shahid Bhagat Singh Nagar
CHAMOLI
BIJNOR
MORADABAD
EAST SINGHBUM
RAICHUR
LAHUL AND SPITI
RUDRA PRAYAG
RUDRA PRAYAG
JAUNPUR
KOLAR
BOUDH
LAHUL AND SPITI
MIRZAPUR
MUZAFFARPUR
JAGATSINGHAPUR
Mulugu
BILASPUR
SALEM
MANDI
SHIMLA
KAPURTHALA
NAINITAL
SHIMLA
BASTI
BASTI
MAU
NAGAON
DHENKANAL
SATNA
AKOLA
KOLAR
SOUTH ANDAMANS
SOLAN
BHADRAK
TIKAMGARH
CHAMPAWAT
BASTI
LOWER SUBANSIRI
ANJAW
BASTI
MUNGER
JAJAPUR
BENGALURU RURAL
HOSHIARPUR
SAMASTIPUR
DEOGHAR
SAMBALPUR
SHIMLA
SOLAN
PATIALA
NORTH DISTRICT
EAST GODAVARI
BALLARI
TUMAKURU
KINNAUR
BIRBHUM
SHIMLA
AZAMGARH
KUSHI NAGAR
EAST SINGHBUM
SHAHDOL
BENGALURU RURAL
TUMAKURU
SAMBA
HOSHIARPUR
JALANDHAR
JHUNJHUNU
SATNA
CHAMBA
CHAMBA
CHAMPAWAT
EAST SINGHBUM
SARAIKELA KHARSAWAN
PURBI CHAMPARAN
GIRIDIH
PITHORAGARH
HASSAN
SOLAN
CHAMPAWAT
BHANDARA
TUMAKURU
DEORIA
SONBHADRA
BANKURA
MEDINIPUR WEST
KODAGU
SOUTH ANDAMANS
CHANDAULI
HAZARIBAGH
SHIVPURI
BENGALURU RURAL
NORTH AND MIDDLE ANDAMAN
CHAMOLI
TEHRI GARHWAL
PURI
RAJNANDGAON
THANJAVUR
SHIMLA
HANUMANGARH
TINSUKIA
JAJAPUR
HASSAN
BARPETA
DHENKANAL
NARSINGHPUR
SATNA
Mahisagar
MEDCHAL MALKAJGIRI
SOLAN
JAUNPUR
ANANTAPUR
THIRUVARUR
BIJNOR
JALPAIGURI
JAGATSINGHAPUR
CHANDRAPUR
SOLAN
ALMORA
PAURI GARHWAL
MEERUT
MEDINIPUR EAST
CHATRA
DEOGHAR
SIDHI
CHITRADURGA
SHIMLA
KATHUA
SHIMLA
PAURI GARHWAL
PAURI GARHWAL
PITHORAGARH
TAWANG
WEST KAMENG
KHORDHA
SAMBALPUR
RAJNANDGAON
BALAGHAT
GANGANAGAR
BASTI
BHANDARA
BHADRADRI KOTHAGUDEM
MANDI
UNA
BIRBHUM
DEOGHAR
BALESHWAR
JAGATSINGHAPUR
GADCHIROLI
HAMIRPUR
PAURI GARHWAL
PITHORAGARH
HAILAKANDI
WARDHA
DAUSA
MIRZAPUR
ANUGUL
CHIKKABALLAPURA
MANDI
BALLIA
LOWER SUBANSIRI
JAJAPUR
DAVANGERE
HAMIRPUR
SUNDARGARH
SHIMLA
CHATRA
GIRIDIH
KALAHANDI
PAURI GARHWAL
HANUMANGARH
AZAMGARH
LAKHIMPUR
REWA
RAMANAGARA
MANDI
SHIMLA
REWA
MANDI
KANGRA
PATIALA
RUDRA PRAYAG
MEDINIPUR WEST
RAISEN
BULDHANA
ALMORA
CHANGLANG
BALESHWAR
BHOPAL
JALANDHAR
EAST SINGHBUM
SAGAR
KANGRA
MANDI
PITHORAGARH
WOKHA
MEDINIPUR WEST
UTTARA KANNADA
KATHUA
AZAMGARH
BULANDSHAHR
SATNA
BILASPUR
AYODHYA
PURNIA
MANDI
JALANDHAR
NAGAON
SHIVAMOGGA
UTTARA KANNADA
LAHUL AND SPITI
AZAMGARH
PASHCHIM CHAMPARAN
MEDINIPUR EAST
CHAMPAWAT
KHERI
SOLAN
SOLAN
ALWAR
HANUMANGARH
WARDHA
CHIKKABALLAPURA

In [7]:
state_totals_second = census.groupby('State').agg({'Population': 'sum','Scheduled Caste population':'sum','Scheduled Tribe population':'sum' })

In [8]:
state_totals_second

,Population,Scheduled Caste population,Scheduled Tribe population
State,,,
ANDAMAN AND NICOBAR ISLANDS,380581,0,28530
ANDHRA PRADESH,49577103,8469278,2740133
ARUNACHAL PRADESH,1383727,0,951821
ASSAM,31205576,2231321,3884371
BIHAR,104099452,16567325,1336573
CHANDIGARH,1055450,199086,0
CHHATTISGARH,25545198,3274269,7822902
DELHI,16787941,2812309,0
GOA,1458545,25449,149275
GUJARAT,60443083,4074480,8917174
HARYANA,25351462,5113615,0
HIMACHAL PRADESH,6864602,1729252,392126
JAMMU AND KASHMIR,12267013,924485,1275106
JHARKHAND,32988134,3985644,8645042
KARNATAKA,61095297,10474992,4248987
KERALA,33406061,3039573,484839
LADAKH,274289,506,218193
LAKSHADWEEP,64473,0,61120
MADHYA PRADESH,72641665,11344907,15317241
MAHARASHTRA,112374333,13275898,10510213
MANIPUR,2855794,97328,1167422
MEGHALAYA,2966889,17355,2555861
MIZORAM,1097206,1218,1036115
NAGALAND,1978502,0,1710973
ODISHA,41980846,7189822,9592130
PUDUCHERRY,1247953,196325,0
PUNJAB,27743338,8860179,0
RAJASTHAN,68548437,12221593,9238534
SIKKIM,610577,28275,206360
TAMIL NADU,72147030,14438445,794697
TELANGANA,35003674,5408800,3177940
THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU,586956,12310,193927
TRIPURA,3673917,654918,1166813
UTTAR PRADESH,199812341,41357608,1134273
UTTARAKHAND,10086292,1892516,291903
WEST BENGAL,91276115,21463270,5296953

In [13]:

state_totals_second['SC caste percentage'] = 100 * state_totals_second['Scheduled Caste population'] / state_totals_second['Population']


state_totals_second['ST percentage'] = 100 * state_totals_second['Scheduled Tribe population'] / state_totals_second['Population']

In [24]:
census['Population involved in agriculture']=100 * (census['Number of main workers as cultivators']+census['Number of main workers as agricultural labourers'])/census['Working population']

In [26]:
state_totals_second = census.groupby('State').agg({'Working population': 'sum','Number of main workers as cultivators':'sum','Number of main workers as agricultural labourers':'sum'})

In [28]:
state_totals_second['Population invloved in agriculture']=100 * (state_totals_second['Number of main workers as cultivators']+state_totals_second['Number of main workers as agricultural labourers'])/state_totals_second['Working population']

In [29]:
state_totals_second

,Working population,Number of main workers as cultivators,Number of main workers as agricultural labourers,Population invloved in agriculture
State,,,,
ANDAMAN AND NICOBAR ISLANDS,152535,12997,2680,10.277641
ANDHRA PRADESH,23080964,3093392,8612238,50.715516
ARUNACHAL PRADESH,587657,248120,20259,45.669328
ASSAM,11969690,3138554,903294,33.767357
BIHAR,34724987,5413181,9537418,43.054297
CHANDIGARH,404136,2169,1396,0.882129
CHHATTISGARH,12180225,3038094,2505999,45.517164
DELHI,5587049,27759,31474,1.060184
GOA,577248,24062,10758,6.032069
GUJARAT,24768955,4747196,4492001,37.301521
HARYANA,8916508,1963311,891273,32.014596
HIMACHAL PRADESH,3559422,919786,68668,27.770071
JAMMU AND KASHMIR,4195761,553460,158402,16.966219
JHARKHAND,13098274,2001362,1238774,24.737122
KARNATAKA,27872597,6038309,5119921,40.032976
KERALA,11619063,544932,919136,12.600569
LADAKH,126952,13009,1117,11.127040
LAKSHADWEEP,18753,0,0,0.000000
MADHYA PRADESH,31579159,8215029,6630881,47.011733
MAHARASHTRA,49427878,11478075,11068928,45.615964
MANIPUR,1304610,466768,45609,39.274343
MEGHALAYA,1185619,411270,114642,44.357589
MIZORAM,486705,202514,26464,47.046568
NAGALAND,974122,420379,22571,45.471717
ODISHA,17544207,3280004,2421135,32.495849
PUDUCHERRY,444968,10763,50607,13.792003
PUNJAB,9897362,1803860,1168021,30.027001
RAJASTHAN,29886255,9845353,2195304,40.288276
SIKKIM,308138,82707,11582,30.599601
TAMIL NADU,32884681,3855375,7234101,33.722316
TELANGANA,16341942,2994215,4589751,46.407985
THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU,278432,24356,6675,11.144912
TRIPURA,1469521,246707,201863,30.524913
UTTAR PRADESH,65814715,15576415,9749915,38.481258
UTTARAKHAND,3872275,1045674,247256,33.389416
WEST BENGAL,34756355,4203767,5869498,28.982513